python/jsonschema_definition.py

#975: Remove 'svm_model_type' definition for 'training'

---

package/schema/jsonschema_definition.py

#1167: Use 'minLength' in 'jsonschema_definitions.py'

---

brain/cache/redis_query.py

#1736: redis_query.py, add missing colon for 'lrem'

---

brain/cache/redis_query.py

#1768: redis_query.py, adjust 'start_redis' docblock

---

brain/cache/redis_query.py

#1776: redis_query.py, remove unnecessary colon

---

brain/session/model_generate.py

#1866: model_generate.py, cache svm title into redis

---

brain/session/model_generate.py

#1869: model_generate.py, cache 'encoded_labels'

---

brain/session/model_generate.py

#1895: model_generate.py, cache 'label_encoder'

---

puppet/manifests/install_sklearn.pp

#1965: install_sklearn.pp, remove '/vagrant/build/'

---

Vagrantfile
puppet/manifests/compile_asset.pp
puppet/manifests/vagrant_mounted.pp

Partial #2046.
**Note:** we still need to add appropriate docblocks within `vagrant_mounted.pp`.  Specifically, within the heredoc upstart script, we need to comment the role of each upstart command.

#2046: Ensure upstart webcompiler scripts autostarts

---

test/linter/.scss-lint.yml

#2093: .scss-lint.yml, remove unnecessary definition

---

puppet/environment/development/modules/system/manifests/log_directory.pp

#2470: Properly define 'directories' variable in 'log_directory.py'

---

.gitignore

#2488: Ignore 'log/webcompiler/' within '.gitignore'

---

puppet/environment/development/modules/compiler/templates/webcompilers.erb

#2590: Remove unnecessary syntax in 'webcompilers.erb'

---

hiera/settings.yaml

#2655: Define 'redis' attributes in vagrant 'settings.yaml'

---

build_docker

#2674: Ensure 'build_docker' runs for OSX

---

README.md

#2712: Adjust 'README.md' to correspond to #5

---

Vagrantfile
hiera.yaml

#2928: Replace hiera version 3 with version 5

---

Vagrantfile
hiera/nodes/aristotle.mongodb.com.yaml
hiera/nodes/confucious.mongodb.com.yaml
hiera/nodes/copernicus.mongodb.com.yaml
hiera/nodes/galileo.mongodb.com.yaml
hiera/nodes/kepler.mongodb.com.yaml
hiera/nodes/laotzu.mongodb.com.yaml
hiera/nodes/plato.mongodb.com.yaml
hiera/nodes/siddhartha.mongodb.com.yaml
hiera/nodes/socrates.mongodb.com.yaml

#2946: Update custom trusty64 box in 'Vagrantfile'

---

src/jsx/import/general/breakpoints.js
src/jsx/import/layout/analysis.jsx
src/jsx/import/navigation/header-menu.jsx
src/jsx/import/navigation/menu-items/results.jsx
src/jsx/import/navigation/nav-bar.jsx
src/jsx/import/navigation/user-menu.jsx
src/package.json
src/scss/_layout.scss
src/scss/_navigation.scss

#3146: Integrate 'UserMenu' with 'NavBar'

---

src/jsx/import/navigation/header-menu.jsx
src/jsx/import/navigation/user-menu.jsx
src/jsx/import/svg/svg-books.jsx
src/jsx/import/svg/svg-home.jsx
src/jsx/import/svg/svg-pencil-note.jsx
src/jsx/import/svg/svg-user.jsx
src/scss/_navigation.scss
src/scss/_variables.scss

#3155: Replace register text with svg in 'HeaderMenu'

---

brain/session/base.py
brain/session/data/dataset.py
brain/validator/dataset.py
brain/validator/settings.py

#3198: Generate verbose 'voluptuous' errors

---

docker-compose.yml
dockerfile/browserify.dockerfile
install_rancher
rancher-template.yml

#3271: Rancher AWS instance unhealthy
