brain/database/retrieve_entity.py
=> #1813: Create 'retrieve_entity.py'

brain/cache/cache_hset.py
Resolves #1815.
**Note:** we had some commit typos.  All commits for this pull request were meant to be committed to #1815.
=> #1815: Create 'cache_hset.py'

brain/cache/cache_model.py
=> #1817: cache_model.py, adjust class constructor

brain/session/model_generate.py
=> #1797: fix tuple typo in 'model_generate.py'

brain/session/model_generate.py
=> #1797: model_generate.py, concatenate '_'

src/js/ajax_session.js
=> #1823: ajax_session.js, adjust 'element'

src/js/ajax_model.js
=> #1807: adjust 'element' in 'ajax_model.js'

web_interface/templates/index.html
=> #1827: index.html, add script tag for 'ajax_feature.js'

src/js/ajax_feature.js
=> #1801: Create 'ajax_feature.js'

brain/session/model_generate.py
=> #1835: Set redis cache for svm properties

web_interface/views.py
=> #1826: Add 'retrieve_feature_properties' to 'views.py'

src/js/ajax_feature.js
=> #1801: ajax_feature.js, send 'session_id' via ajax

web_interface/views.py
=> #1826: views.py, 'import Cache_Hsset'

src/js/ajax_feature.js
=> #1801: ajax_feature.js, change semicolon to comma

src/js/ajax_feature.js
=> #1801: ajax_feature.js, remove 'JSON.stringify'

brain/cache/cache_hset.py
=> #1815: cache_hset.py, define 'return' in 'uncache'

web_interface/views.py
Resolves #1792, Resolves #1826.
=> #1792, #1826: Uncache feature labels, return errors

brain/cache/cache_hset.py
=> #1815: cache_hset.py, return python dict

web_interface/views.py
=> #1792: views.py, fix typo, adjust docblock

src/js/html_form.js
=> #1828: Implement 'feature_properties' in 'html_form.js'

src/js/ajax_feature.js
=> #1801: ajax_feature.js, 'indep_variable' input elements

brain/session/model_generate.py
=> #1835: Define feature labels in redis cache

src/js/ajax_feature.js
=> #1801: ajax_features.js, change classname for fieldset

src/js/ajax_feature.js
=> #1801: ajax_feature.js, change fieldset legend

src/js/html_form.js
=> #1828: Remove previous 'fieldset_prediction_input'

src/js/html_form.js
=> #1828: html_form.js, remove 'fieldset_prediction_input'

src/js/html_form.js
=> #1828: dynamically add submit button

src/js/form_validator.js
=> #1848: Validate 'indep_variable[]' in 'form_validator.js'

brain/session/model_generate.py
=> #1835: model_generate.py, append feature labels

brain/cache/cache_model.py
=> #1862: cache_model.py, define 'uncache' method

src/js/ajax_model.js
=> #1807: ajax_model.js, adjust 'value' property

src/js/ajax_model.js
=> #1807: ajax_model.js, revert changes made in b9f734b

brain/session/model_generate.py
=> #1866: model_generate.py, minor comment change

brain/session/model_use.py
=> #1078: Implement 'class' in 'model_use.py'

brain/session/model_use.py
=> #1078: model_use.py, add missing parantheses

src/js/ajax_data.js
=> #376: Add 'indep_variable[]' condition

brain/converter/restructure_data.py
=> #1875: Implement 'request.form.getlist'

brain/load_data.py
=> #1873: Implement 'svm_prediction' in 'load_data.py'

brain/session/model_use.py
=> #1078: Remove unnecessary prediction and validation

brain/session/model_use.py
=> #1078: model_use.py, import required classes

src/js/ajax_data.js
=> #376: ajax_data.js, remove 'console.log'

brain/session/model_use.py
=> #1078: fix various typos in 'model_use.py'

src/js/ajax_feature.js, src/js/html_form.js
=> #1858: Rename css class in 'html_form.js'

brain/session/model_use.py, src/js/ajax_data.js, src/js/ajax_feature.js, src/js/form_validator.js
=> #1856: Rename 'indep_variable[]' in 'ajax_feature.js'

brain/schema/jsonschema_definition.py, src/js/form_validator.js
=> #1883: Remove 'svm_indep_variable' from validations

src/js/html_form.js
=> #1828: html_form.js, adjust comment

src/js/ajax_feature.js
=> #1801: remove previous fieldset instance

brain/converter/serialize_model.py
=> #1892: Allow numpy objects in 'serialize_model.py'

brain/converter/serialize_model.py
=> #1894: Allow LabelEncoder objects

brain/load_data.py
=> #1889: Implement 'Base' class methods in 'load_data.py'

brain/validator/validate_settings.py
=> #1122: add 'model_generate' in 'validate_settings.py'

brain/session/base.py
=> #1899: base.py, remove duplicated 'validate' call

brain/session/model_generate.py, brain/session/model_predict.py
=> #1888: Implement 'super' into 'model_xx.py' constructor

brain/schema/jsonschema_definition.py
=> #1143: jsonschema_definition.py, add schema

brain/session/base.py
=> #1899: base.py, correctly append to 'self.list_error'

brain/schema/jsonschema_definition.py
=> #1602: Adjust schemas in 'jsonschema_definition.py'

brain/session/model_predict.py
=> #1906: model_predict.py, return 'texual_label'

src/js/ajax_data.js
=> #1908: Get predicted result in 'ajax_data.js'

brain/session/model_predict.py
=> #1906: return inner content of 'texual_label'

src/js/form_validator.js
=> #1911: adjust regex for 'numericOnly'

src/js/form_validator.js
=> #1911: form_validator.js, adjust float regex

.gitignore
=> #1489: .gitignore, exception for 'Vagrantfile', and 'manifests/'

Vagrantfile
=> #1929: Vagrantfile, add initial file

brain/converter/convert_upload.py, web_interface/static/data/xml/sample-1.xml, web_interface/static/data/xml/sample.xml
=> #1925: Convert 'entity' to 'observation' in sample xml

brain/session/model_generate.py, brain/session/model_predict.py, web_interface/views.py
=> #1915: Rename 'svm_xx' to 'svm_rbf_xx'

README.md
=> #779: README.md, change references of '/var/www'

README.md
=> #779: README.md, change minor syntax

README.md
=> #779 README.md, fix typo

Vagrantfile
=> #1933: Vagrantfile, define port forwarding

Vagrantfile
=> #1933: Vagrantfile, adjust guest port

puppet/Puppetfile
=> #1959: Puppetfile, minor comment change

puppet/Puppetfile
=> #1970: (mistake) Add 'scikit-learn' to 'Puppetfile'

puppet/Puppetfile
=> #1972: Puppetfile, add 'vcsrepo' puppet module

.gitmodules, Vagrantfile, puppet/manifests/install_sklearn.pp
=> #1965: Create 'install_sklearn.pp' manifest file

puppet/Puppetfile
=> #1975: Puppetfile, add 'git' module

Vagrantfile
=> #1979: Vagrantfile, implement 'vagrant-triggers'

Vagrantfile
=> #1979: Vagrantfile, minor spacing change

puppet/manifests/install_sklearn.pp
=> #1965: install_sklearn.pp, reinsert logic

Vagrantfile
=> #1979: Vagrantfile, add '-p' flag

puppet/manifests/install_sklearn.pp
=> #1965: install_sklearn.pp, minor comment change

.gitignore
=> #1977: .gitignore, remove exception

Vagrantfile
=> #1966, Vagrantfile, adjust docblocks

puppet/Puppetfile
=> #1978: Puppetfile, add 'mariadb' module

Vagrantfile
=> #1966: Vagrantfile, minor language change

Vagrantfile, puppet/manifests/install_packages.pp, puppet/manifests/install_puppet_librarian.pp
=> #1959: Install 'librarian-puppet' via manifest

setup.py
=> #1962: setup.py, remove file

puppet/manifests/setup_database.pp
=> #1962: Ensure proper command sequence

puppet/manifests/setup_database.pp
=> #1962: setup_database.pp, minor comment change

.gitignore, puppet/.gitignore
=> #1996: Transfer '.gitignore' logic

Vagrantfile
=> #1996: Vagrantfile, remove 'vagrant-triggers' plugin

puppet/Puppetfile
=> #2001: Puppetfile, add reference to 'python' module

puppet/Puppetfile
=> #2001: Puppetfile, remove unnecessary comma (typo)

puppet/Puppetfile
=> #2006: Puppetfile, add 'puppet-sys' module

puppet/manifests/start_webserver.pp
=> #1997: start_webserver.pp, adjust docblock

puppet/manifests/start_webserver.pp
=> #1997: start_webserver.pp, minor language change

puppet/manifests/install_packages.pp, puppet/manifests/start_webserver.pp
=> #1997: Implement flask upstart script

puppet/manifests/start_webserver.pp
=> #1997: start_webserver.pp, remove unnecessary 'notify'

puppet/manifests/start_webserver.pp
=> #1997: ensure proper 'pre-stop script' logs

Vagrantfile, puppet/Puppetfile, puppet/manifests/configure_system.pp
=> #2014: Implement puppet 'timezone' module

puppet/manifests/compile_asset.pp
=> #1963: Correctly implement webcompilers

puppet/manifests/compile_asset.pp
=> #1963: Vagrantfile, reference 'compile_asset.pp' manifest

.gitignore
=> #1964: .gitignore, remove 'setup.py'

Vagrantfile, puppet/manifests/compile_asset.pp, puppet/scripts/imagemin, puppet/scripts/sass, puppet/scripts/uglifyjs
=> #1963: Fix webcompiler implementation

Vagrantfile, puppet/manifests/configure_system.pp
=> #2025: Ensure linux line endings in 'configure_system.pp'

puppet/scripts/sass
=> #2019: sass, correctly implement bash sass script

puppet/Puppetfile, puppet/manifests/compile_asset.pp
=> #2014: Implement puppet 'timezone' module v.0.1.3

puppet/manifests/install_packages.pp
=> #2030: install_packages.pp, remove 'npm-watch' package

puppet/manifests/compile_asset.pp
=> #1963: compile_asset.pp, remove duplicate code

puppet/manifests/compile_asset.pp
=> #1963: compile_asset.pp, remove unnecessary code

puppet/manifests/compile_asset.pp
=> #1963: compile_asset.pp, add missing closing bracket

app.py
=> #1933: app.py, allow connection from all IPs

puppet/manifests/install_packages.pp
=> #1949: install_packages.pp, adjust 'timeout'

puppet/manifests/configure_system.pp
=> #2025: Remove linux line ending conversion

puppet/manifests/compile_asset.pp
=> #1963: compile_asset.pp, use dos2unix for webcompilers

Vagrantfile
=> #2043: Vagrantfile, add 'vagrant-vbguest' package

Vagrantfile, brain/database/db_query.py, puppet/manifests/setup_database.pp, puppet/scripts/setup_tables.py
=> #1962: Initialize database tables with 'provisioner' user

puppet/manifests/setup_database.pp
=> #1962: Correctly provision database

puppet/manifests/vagrant_mounted.pp
=> #2046: Ensure upstart webcompiler scripts autostarts

puppet/manifests/vagrant_mounted.pp
=> #2046: vagrant_mounted.pp, adjust docblock for 'script'

puppet/Puppetfile
=> #2051: Puppetfile, adjust URL references using SSH

puppet/manifests/vagrant_mounted.pp
=> #2046: vagrant_mounted.pp, uncomment 'notify'

puppet/manifests/compile_asset.pp
=> #2046: compile_asset.pp, add 'refreshonly' attribute

puppet/manifests/compile_asset.pp
=> #2056: 'touch' nonempty directories for webcompiler build

README.md
=> #1934: README.md, remove 'linux packages' section

README.md
=> #2060: README.md, remove 'GIT Submodule'

README.md
Resolves #1930, and Resolves #1941 (duplicate).
=> #1930: Define 'Installation' section in 'README.md'

README.md
=> #2062: README.md, move 'jQuery Validation' to wiki page

README.md
=> #2063: README.md, move 'JSON Schema' to wiki page

README.md
=> #2069: Adjust 'Testing / Execution' section

README.md
=> #2069: README.md, minor language change

README.md
=> #2052: Create 'Preconfiguration' subsection

README.md
=> #2052: README.md, minor language change

README.md
=> #2052: README.md, mention change 'cwd' before ssh key generation

puppet/manifests/compile_asset.pp
=> #2056: properly touch webcompiler source files

README.md
=> #2052: README.md, add missing notes on ssh

Vagrantfile, puppet/Puppetfile, puppet/manifests/start_webserver.pp
=> #2042: Ensure flask server starts on system boot

puppet/Puppetfile
=> #2083: Puppetfile, remove 'nginx', and 'uwsgi'

brain/session/base_data.py, brain/validator/validate_mime.py, src/js/form_validator.js
=> #2084: Change mime type, to file extension validation

brain/load_data.py, brain/session/base_data.py, brain/validator/validate_file_extension.py
=> #2096: Rename 'validate_mime.py'

puppet/scripts/Puppetfile
=> #204: Puppetfile, fix 'git' path references

puppet/scripts/Puppetfile
=> #204: Puppetfile, add comment

puppet/Puppetfile
=> #204: add comment within Puppetfile

.travis.yml
=> #2091: .travis.yml, install, and implement jshint

.gitignore, .travis.yml, test/linter/.scss-lint.yml
=> #2093: .travis.yml, 'gem install scss_lint'

test/linter/.scss-lint.yml
=> #2093: .scss-lint.yml, add docblock

.travis.yml, test/linter/.scss-lint.yml
=> #2093: remove 'severity: warning' from '.scss-lint.yml'

.travis.yml
=> #2092: .travis.yml, implement 'puppet-lint'

test/linter/.scss-lint.yml
=> #2093: remove '.scss-lint.yml'

.travis.yml
=> #2114: .travis.yml, validate Puppetfile with rubocop

.travis.yml
=> #209: .travis.yml, remove '--config test/linter/.scss-lint.yml'

interface/views.py
=> #2070: views.py, reference '/interface' directory

puppet/scripts/imagemin, puppet/scripts/sass, puppet/scripts/uglifyjs
=> #2070: reference 'interface' directory for webcompilers

.travis.yml, puppet/manifests/compile_asset.pp
=> #2070: correctly reference 'interface' directory

interface/views.py
Partial #2070.
**Note:** our earlier pull requests have made the master branch unstable.  However, this should be the last *partial* pull request to this corresponding issue, since it repairs the master branch back to a working state.
=> #2070: views.py, change 'and' to 'or'

brain/load_data.py
=> #2123: fix 'AttributeError' on 'validate_mime_type'

.gitignore
=> #2125: .gitignore, do not ignore '/interface/' directory

.gitignore
=> #2127: .gitignore, remove some files from exlamation

.gitignore
=> #2129: .gitignore, ignore all python scripts, generically

interface/static/data/json/sample-2.json
=> #2134: sample-2.json, add file

README.md
=> #2136: README.md, correct link to 'JSON sample datasets'

.travis.yml
=> #2131: .travis.yml, implement jsonlint

interface/static/data/json/programmatic_interface/sample-1.json
=> #2141: sample-1.json, define 'properties' attribute

interface/static/data/json/programmatic_interface/sample-1.json
=> #2141: Restructure 'sample-1.json' to include 'settings'

interface/static/data/json/programmatic_interface/sample-1.json
=> #2141: sample-1.json, remove array structure

.travis.yml, interface/static/data/csv/temp.csv
=> #2132: Implement csvlint for sample datasets

interface/static/data/json/web_interface/sample.json
=> #2151: sample.json, trivially reindent

interface/static/data/json/programmatic_interface/sample-model-generate.json
=> #2155: Add 'sample-model-generate.json'

brain/database/save_observation.py, brain/session/base.py
=> #2116: Fix travis validation errors (partial)

interface/__init__.py
=> #2158: __init__.py, resolve 'cannot import name app'

brain/session/base.py
=> #2160: base.py, correctly attain 'error' attribute if exist

interface/views.py
=> #2162: views.py, adjust indentation

brain/load_data.py, interface/static/data/json/programmatic_interface/sample-model-generate.json, interface/views.py, test/programmatic_interface/pytest_session.py
=> #2148: Add 'model_predict' programmatic interface (API)

interface/static/data/json/programmatic_interface/sample-model-predict.json
=> #2165: sample-model_predict.json, add file

interface/views.py, test/programmatic_interface/pytest_session.py
=> #2147: Add 'model_generate' programmatic API

README.md
=> #2172: README.md, fix broken links in 'Web Interface'

README.md
=> #2071: Adjust 'Testing / Execution' section in 'README.md'

brain/validator/validate_settings.py
=> #1121: validate_settings.py, validate 'model_prediction'

README.md
=> #2110: Add 'Support' section in 'README.md'

interface/views.py
=> #2178: views.py, remove 'print jeff'

brain/load_data.py, brain/session/model_predict.py
=> #1849: Validate 'prediction_input[]' values

brain/load_data.py, brain/session/model_predict.py, brain/validator/validate_settings.py
=> #1849: Validate 'prediction_input[]' values as settings

README.md
=> #2180: Define 'Test Scripts' section in 'README.md'

.travis.yml
=> #2189: .travis.yml, adjust comments

README.md
=> #2192: Reference contributing styleguide in 'README.md'

README.md
=> #2192: README.md, move 'Contributing' section

README.md
=> #2195: README.md, change 'repot' to 'repo'

README.md
=> #2195: README.md, change port # reference

brain/converter/convert_upload.py, brain/converter/restructure_data.py
=> #2116: Resolve remaining python lint

.travis.yml
=> #2200: .travis.yml, lint all markdown(s) recursively

puppet/manifests/vagrant_mounted.pp
=> #2205: vagrant_mounted.pp, double quoted heredoc

puppet/manifests/compile_asset.pp, puppet/manifests/start_webserver.pp, puppet/manifests/vagrant_mounted.pp
=> #2207: Revert manifests with upstart scripts to 0.1

src/js/ajax_graphic.js, src/js/jquery-validate.js
=> #2210: Fix 'Uncaught Reference Error', 'TypeError'

brain/session/base_data.py
=> #2209: base_data.py, remove sorted validation on labels

brain/session/base_data.py
=> #2209: base_data.py, remove observation label logic

.travis.yml, puppet/scripts/puppet_updater.sh
=> #2186: .travis.yml, implement 'shellcheck'

interface/static/data/xml/dataset.xsd, interface/static/data/xml/sample-1.xml, interface/static/data/xml/sample.xml
=> #2204: Define DTD (or schema) for xml dataset

.travis.yml, interface/static/data/xml/dataset.xsd, interface/static/data/xml/sample-1.xml, interface/static/data/xml/sample.xml
=> #2204: adjust 'xsd' schema validation reference

.travis.yml, interface/static/data/xml/dataset.xsd, interface/static/data/xml/sample-1.xml, interface/static/data/xml/sample.xml
=> #2204: Define xml schema for xml dataset

.travis.yml, interface/static/data/xml/dataset.xsd
=> #2204: validate '*.xsd' files

.gitignore, contributing.md
=> #2223: Move 'Contributing' wiki to 'Contributing.md'

README.md, contributing.md
=> #2223: Adjust references to 'license.md'

contributing.md
=> #2223: contributing.md, minor language change

puppet/manifests/compile_asset.pp, puppet/template/webcompilers.erb
=> #2023: Implement puppet template for webcompilers

puppet/manifests/compile_asset.pp
=> #2023: compile_asset.pp, adjust docblock

puppet/manifests/start_webserver.pp, puppet/template/webserver.erb
=> #2229: Implement puppet template for flask script

puppet/manifests/vagrant_mounted.pp, puppet/template/vagrant_mounted.erb
=> #2230: Implement puppet template for vagrant-mounted

puppet/manifests/vagrant_mounted.pp, puppet/template/vagrant_mounted.erb
=> #2242: Vagrant build hangs on 'vagrant-mounted'

src/js/html_form.js, src/js/jquery-2.1.1.js
=> #2246: Form pages do not dynamically generate pages

interface/templates/index.html, src/js/html_form.js
=> #2248: KeyError: 'svm_session' arising from 'data_new'

puppet/scripts/imagemin, puppet/scripts/sass, puppet/scripts/uglifyjs
=> #2253: Incorrect files references 'CLOSE_WRITE,CLOSE'

puppet/manifests/compile_asset.pp, puppet/template/touch_source.erb
=> #2255: Ensure source files compile on initial build

src/js/ajax_session.js
=> #2257: Cannot append with web-interface 'data_append'

src/js/ajax_feature.js, src/js/ajax_model.js
=> #2259: Cannot generate prediction during 'model_predict'

src/js/html_form.js
=> #2261: Multiple 'submit' buttons created

puppet/scripts/imagemin, puppet/scripts/sass, puppet/scripts/uglifyjs
=> #2252: Adjust docblock for each bash webcompiler

src/js/html_form_delegator.js, src/scss/style.scss
=> #2250: Ensure added 'input' elements are block positioned

README.md
=> #2267: Adjust note regarding linting

src/js/html_form.js
=> #2270: Unselecting model does not clear form

README.md
=> #2272: Small grammar change in 'README.md'

brain/cache/cache_model.py
=> #2274: cache_model.py, add 'else' case for no model found

puppet/manifests/install_packages.pp, src/js/react-dom.js, src/js/react.js, test/config/.jscs.json, test/config/.jshintignore
=> #2280: Add reactjs, and required packages

README.md
=> #2284: README.md, adjust reference for vagrant wiki page

puppet/manifests/install_packages.pp
=> #2286: Install babel plugin presets

puppet/scripts/browserify
=> #2288: Create upstart to browserify reactjs scripts

puppet/scripts/browserify
=> #2288: browserify, adjust comment

puppet/manifests/compile_asset.pp
=> #2292: compile_asset.pp, add reference to 'browserify'

.travis.yml, test/config/eslint.json
=> #2293: .travis.yml, lint 'jsx' files

puppet/manifests/compile_asset.pp
=> #2294: Condense variables into hashes in 'compile_asset.pp'

puppet/manifests/compile_asset.pp
=> #2304: compile_asset.pp, fix minor typos

puppet/manifests/compile_asset.pp
=> #2306: compile_asset.pp, minor comment change

puppet/scripts/browserify
=> #2309: Error: Cannot find module 'babelify'

puppet/Puppetfile, puppet/manifests/install_packages.pp
=> #2311: Update nodejs (5.2.x), and npm (3.3.x)

puppet/scripts/browserify
=> #2308: Ensure only '*.jsx' files compile javascript

puppet/manifests/install_packages.pp
=> #2309: install_packages.pp, use '--no-bin-links'

puppet/scripts/browserify, puppet/scripts/imagemin
=> #2308: browserify, minor syntax adjustments

puppet/scripts/uglifyjs
=> #2316: Ensure only js files minify with uglifyjs

.gitignore, puppet/scripts/browserify
=> #2291: Ensure compiled jsx files are not versioned

puppet/scripts/sass
=> #2317: Ensure only scss files minify with sass

puppet/scripts/uglifyjs
=> #2322: Adjust docblock within 'uglifyjs'

puppet/scripts/imagemin
=> #2324: Adjust docblock within 'imagemin'

puppet/scripts/browserify
=> #2291: browserify, properly ignore compiled jsx files

README.md
=> #2302: Document how to clone from release

README.md
=> #2302: Minor language change regarding 'cloning'

README.md
=> #2302: README.md, minor language change

README.md
=> #2302: fix additional typos

src/jsx/select_session.jsx
=> #2334: select_session.jsx, fix indentation

contributing.md
=> #2343: Remove extra spacing within 'contributing.md'

contributing.md
=> #2345: contributing.md, fix links

interface/templates/index.html
=> #2347: Move reactjs <script> to last element in <body>

puppet/scripts/sass
=> #2350: Ensure scss partials does not compile

license.md
=> #2354: Update 'license.md' copyright date

src/js/ajax_feature.js, src/js/ajax_model.js, src/js/ajax_session.js, src/jsx/import/data_append.jsx, src/jsx/import/data_new.jsx, src/jsx/import/model_generate.jsx, src/jsx/import/model_predict.jsx, src/jsx/import/supply_dataset_file.jsx, src/jsx/import/supply_predictors.jsx, src/jsx/select_session.jsx, test/config/eslint.json
=> #2332: Refactor 'html_form.js' using reactjs framework

src/jsx/README.md
=> #2360: README.md, adjust language

src/jsx/import/supply_dataset_file.jsx, src/jsx/import/supply_dataset_url.jsx, src/scss/style.scss
=> #2367: Position 'Add more', 'Remove' button in jsx and css

test/config/.jscs.json
=> #2222: Ensure javascript does not exceed 80 chars

src/jsx/import/validator/valid_float.js
=> #2353: Create 'valid_float.js' to verify float type

src/jsx/import/validator/valid_int.js
=> #2377: Create 'valid_int.js' to verify int type

src/jsx/import/validator/valid_file.js
=> #2352: Create 'valid_file.js' to verify file extension

src/jsx/import/validator/valid_string.js
=> #2376: Create 'valid_string.js' to verify string type

contributing.md
=> #2384: Update links within 'contributing.md'

src/jsx/select_session.jsx
=> #2388: Remove import resulting in 'Error: Cannot find module'

test/config/eslint.json
=> #2390: Resolve 'eslint' parsing errors, by defining parser

src/jsx/import/validator/valid_url.js
=> #2395: Create 'valid_url.js' to verify url

src/jsx/import/validator/valid_int.js, src/jsx/import/validator/valid_string.js, src/jsx/import/validator/valid_url.js
=> #2397: Condense react validators, correctly implement 'typeof'

src/jsx/import/validator/valid_file.js, src/jsx/import/validator/valid_float.js, src/jsx/import/validator/valid_int.js, src/jsx/import/validator/valid_string.js, src/jsx/import/validator/valid_url.js
=> #2399: Add 'default' within 'export' for react validators

Vagrantfile
=> #2337: Ensure 'vagrant destroy' removes corresponding asset

Vagrantfile
=> #2404: Add '-f' flags for 'config.trigger.after'

Vagrantfile
=> #2406: Ensure 'puppet/modules' directory on 'vagrant up'

Vagrantfile
=> #2416: Add missing 'end' in 'Vagrantfile'

.travis.yml, Dockerfile, puppet/environment/development/modules/package/manifests/inotify_tools.pp, puppet/environment/development/modules/package/manifests/jsonschema.pp, puppet/environment/development/modules/package/manifests/redis_client.pp, puppet/environment/development/modules/package/manifests/redis_server.pp, puppet/environment/development/modules/package/manifests/six.pp, puppet/environment/development/modules/package/manifests/sklearn.pp, puppet/environment/development/modules/package/manifests/sklearn_dependencies.pp, puppet/environment/development/modules/package/manifests/webcompilers.pp, puppet/environment/development/modules/package/manifests/xmltodict.pp
=> #2392: Ensure all packages install from major release version

puppet/environment/development/modules/compiler/scripts/imagemin
=> #2263: Ensure only img files are minified with imagemin

puppet/environment/development/modules/compiler/scripts/browserify
=> #2336: Prevent duplicate entry in '/vagrant/src/js/.gitignore'

src/jsx/import/input-data/supply_dataset_file.jsx, src/jsx/import/input-data/supply_dataset_url.jsx, src/jsx/import/input-data/supply_predictors.jsx, src/jsx/import/result/result_display.jsx, src/jsx/import/session-type/data_append.jsx, src/jsx/import/session-type/data_new.jsx, src/jsx/import/session-type/model_generate.jsx, src/jsx/import/session-type/model_predict.jsx, src/jsx/select_session.jsx, test/config/eslint.json
=> #2380: Implement max line length for eslint

src/jsx/import/input-data/supply_dataset_file.jsx, src/jsx/import/input-data/supply_dataset_url.jsx
=> #2429: Ensure submit button clears, when no dataset selected

src/jsx/import/validator/valid_file.js
=> #2433: Remove jquery from javascript validators

interface/views.py
=> #2401: views.py, properly acquire 'session_id'

src/jsx/import/input-data/supply_predictors.jsx, src/jsx/import/session-type/data_append.jsx, src/jsx/import/session-type/model_generate.jsx, src/jsx/import/session-type/model_predict.jsx
=> #2437: Reactjs can only update a mount(ed|ing) component

.travis.yml, src/js/ajax_caller.js
=> #2443: Resolve travis jshint, and bootlint introduced via #2413

src/jsx/import/input-data/supply_dataset_url.jsx, src/jsx/import/input-data/supply_predictors.jsx, src/jsx/import/session-type/model_predict.jsx
=> #2445: Clear components when another model chosen

src/jsx/import/input-data/supply_predictors.jsx, src/jsx/import/session-type/data_append.jsx, src/jsx/import/session-type/model_generate.jsx, src/jsx/import/session-type/model_predict.jsx
=> #2447: Reduce redundant fetch 'if (this.mounted)', add spinner

src/jsx/import/session-type/model_generate.jsx, src/jsx/select_session.jsx
=> #1917: Add kernel types in 'html_form.js'

app.py
=> #2441: Create server logs associated with 'app.py'

app.py
=> #2453: Add comments with respect to 'access.log' in 'app.py'

app.py
=> #2455: Remove unnecessary 'debug=True' from 'app.py'

Vagrantfile, src/jsx/support_vector.jsx
=> #2451: support_vector.jsx, adjust docblock, and 'Vagrantfile'

brain/database/db_query.py
=> #2473: 'IndexError' within 'model_generate.py'

.gitignore
=> #2468: Ensure '*.log' files ignored within 'log/' directory

settings.py
=> #2467: Adjust docblocks in 'settings.py'

brain/session/model_generate.py
=> #2463: model_generate.py, remove logging logic

puppet/environment/development/modules/database/manifests/bindings.pp, puppet/environment/development/modules/database/manifests/client.pp, puppet/environment/development/modules/database/manifests/database.pp, puppet/environment/development/modules/database/manifests/server.pp, puppet/environment/development/modules/package/manifests/sklearn.pp, puppet/environment/development/modules/sklearn/manifests/build_sklearn.pp, puppet/environment/development/modules/sklearn/manifests/install_sklearn.pp, puppet/environment/development/modules/system/manifests/build_directory.pp, puppet/environment/development/modules/vagrant/manifests/start.pp
=> #2469: Consistent puppet directive title indentation

Vagrantfile, puppet/environment/development/modules/compiler/scripts/browserify, puppet/environment/development/modules/compiler/scripts/imagemin, puppet/environment/development/modules/compiler/scripts/sass, puppet/environment/development/modules/compiler/scripts/uglifyjs, puppet/environment/development/modules/compiler/templates/webcompilers.erb, puppet/environment/development/modules/system/manifests/log_directory.pp
=> #2466: Move webcompiler logs into 'log/webcompiler/'

puppet/environment/development/modules/compiler/scripts/browserify, puppet/environment/development/modules/compiler/scripts/imagemin, puppet/environment/development/modules/compiler/scripts/sass, puppet/environment/development/modules/compiler/scripts/uglifyjs, puppet/environment/development/modules/compiler/templates/webcompilers.erb, puppet/environment/development/modules/webserver/templates/webserver.erb
=> #2457: Condense webcompiler log file pairs into one log file

puppet/environment/development/modules/compiler/templates/webcompilers.erb, puppet/environment/development/modules/webserver/templates/webserver.erb
=> #2457: Ensure log entries prefixed with correct datetime

puppet/environment/development/modules/compiler/scripts/browserify, puppet/environment/development/modules/compiler/scripts/imagemin, puppet/environment/development/modules/compiler/scripts/sass, puppet/environment/development/modules/compiler/scripts/uglifyjs
=> #2457: ensure log dates enclosed with brackets

app.py, puppet/environment/development/modules/system/manifests/log_directory.pp, puppet/environment/development/modules/webserver/templates/webserver.erb
=> #2491: Condense flask log pair into one log file

.travis.yml
=> #2472: Ensure 'puppet-lint' properly implemented

.gitignore
=> #2497: Ignore 'log/application/' within '.gitignore'

.travis.yml, puppet/environment/development/modules/compiler/manifests/webcompilers.pp
=> #2496: Remediate puppet syntax correspondinng to #2472

puppet/environment/development/modules/package/manifests/fetch.pp
=> #2484: Ensure all pip packages install from major release

.gitignore
=> #2505: Ignore 'log/webserver/' within '.gitignore'

puppet/environment/development/modules/compiler/manifests/webcompilers.pp
=> #2472: trivial merge

brain/database/db_query.py, log/logger.py
=> #2478: Ensure application logs into designated logs

src/jsx/import/kernel/sv_kernel.jsx, src/jsx/import/session-type/model_generate.jsx
=> #2450: Create 'sv_kernel.jsx' to contain SVC / SVR kernels

puppet/environment/development/modules/compiler/scripts/browserify, puppet/environment/development/modules/compiler/scripts/imagemin, puppet/environment/development/modules/compiler/scripts/sass, puppet/environment/development/modules/compiler/scripts/uglifyjs
=> #2510: Datetime not properly adjusting per log entry

src/jsx/import/session-type/model_generate.jsx
=> #2512: Temporarily restore 'model_generate.jsx'

interface/views.py
=> #2515: Remove 'GET' protocol within 'views.py'

brain/session/predict/__init__.py
=> #2520: Add '__init__.py' in 'brain/session/predict/'

brain/session/model/__init__.py
=> #2519: Add '__init__.py' in 'brain/session/model/'

brain/converter/convert_upload.py, brain/converter/restructure_data.py, brain/database/retrieve_feature.py, brain/database/retrieve_session.py, brain/database/save_entity.py, brain/database/save_feature.py, brain/database/save_observation.py, brain/load_data.py, brain/schema/jsonschema_definition.py, brain/session/base.py, brain/session/base_data.py, brain/session/data_append.py, brain/session/data_new.py, brain/session/model_generate.py, brain/session/model_predict.py, brain/validator/validate_dataset.py, brain/validator/validate_file_extension.py, brain/validator/validate_settings.py, interface/views.py, src/jsx/import/general/submit.jsx, src/jsx/import/input-data/supply_dataset_file.jsx, src/jsx/import/input-data/supply_dataset_url.jsx, src/jsx/import/input-data/supply_predictors.jsx, src/jsx/import/session-type/data_append.jsx, src/jsx/import/session-type/data_new.jsx, src/jsx/import/session-type/model_generate.jsx, src/jsx/import/session-type/model_predict.jsx, src/jsx/support_vector.jsx, src/scss/style.scss
=> #1922: Remove 'svm_' prefix in web application

README.md
=> #2528: Ensure travis-ci button predicated on master branch

brain/session/model_generate.py
=> #2474: Refactor error 'print' statements into python logging

log/logger.py
=> #2533: Predefine 'level' argument for 'Logger' class

brain/load_data.py, brain/session/model_predict.py, brain/session/predict/svm.py
=> #2517: Move subset of 'model_predict.py' into a python module

log/logger.py
=> #2543: Preprend filename to log message within 'logger.py'

brain/converter/dataset/json_converter.py
=> #2541: Validate dataset(s) within 'json.py'

brain/converter/dataset/csv_converter.py, brain/converter/dataset/json_converter.py, brain/converter/dataset/xml_converter.py
=> #2540: Implement logger within convert modules

brain/session/model/svm.py, brain/session/model_generate.py
=> #2516: Move subset of 'model_generate.py' into a module

brain/session/model/svm.py, brain/session/model_generate.py, src/jsx/import/kernel/sv_kernel.jsx
=> #1916: Add 'kernel_type' logic in 'model_generate.py'

test/programmatic_interface/pytest_session.py
=> #2551: Adjust python unit tests

interface/static/data/json/programmatic_interface/svm/svm-data-append.json, interface/static/data/json/programmatic_interface/svm/svm-data-new.json, interface/static/data/json/programmatic_interface/svm/svm-model-generate.json, interface/static/data/json/programmatic_interface/svm/svm-model-predict.json, interface/static/data/json/programmatic_interface/svr/svr-model-generate.json
=> #2554: Add 'kernel_type' attribute to programmatic datasets

README.md, interface/static/data/json/programmatic_interface/svm/svm-data-append.json, interface/static/data/json/programmatic_interface/svm/svm-data-new.json, interface/static/data/json/programmatic_interface/svm/svm-model-generate.json, interface/static/data/json/programmatic_interface/svm/svm-model-predict.json, interface/static/data/json/programmatic_interface/svr/svr-data-append.json, interface/static/data/json/programmatic_interface/svr/svr-data-new.json, interface/static/data/json/programmatic_interface/svr/svr-model-generate.json, interface/static/data/json/programmatic_interface/svr/svr-model-predict.json
=> #2557: Resolve unit test traceback for programmatic interface

src/jsx/import/session-type/model_generate.jsx
=> #2560: Change 'polynomial' kernel to 'poly'

settings.yml
=> #2563: settings.py, remove trailing slash

puppet/environment/development/modules/webserver/manifests/service.pp, puppet/environment/development/modules/webserver/templates/webserver.erb
=> #2568: 'app.py' does not automatically start on 'vagrant up'

settings.yml
=> #2570: Fix minor typo in 'settings.yml' docblock

puppet/environment/development/modules/compiler/manifests/initial_compile.pp, puppet/environment/development/modules/compiler/manifests/webcompilers.pp, puppet/environment/development/modules/compiler/templates/webcompilers.erb, puppet/environment/development/modules/database/manifests/database.pp, puppet/environment/development/modules/database/manifests/server.pp, puppet/environment/development/modules/database/scripts/setup_tables.py, puppet/environment/development/modules/package/manifests/react_presets.pp, puppet/environment/development/modules/package/manifests/sklearn.pp, puppet/environment/development/modules/sklearn/manifests/build_sklearn.pp, puppet/environment/development/modules/sklearn/manifests/install_sklearn.pp, puppet/environment/development/modules/system/manifests/build_directory.pp, puppet/environment/development/modules/system/manifests/log_directory.pp, puppet/environment/development/modules/system/manifests/webcompiler_directory.pp, puppet/environment/development/modules/webserver/manifests/service.pp, puppet/environment/development/modules/webserver/templates/webserver.erb, settings.yml
=> #2565: Standardize common puppet patterns

README.md
=> #2574: Add vbox extension pack to 'README.md'

puppet/environment/development/modules/database/manifests/server.pp, puppet/environment/development/modules/database/scripts/setup_tables.py
=> #2536: Define sql database structure for SVR

hiera/settings.yaml, puppet/environment/development/modules/database/scripts/setup_tables.py
=> #2578: Move args in 'setup_tables.py' into 'settings.yaml'

app.py, brain/database/retrieve_entity.py, brain/database/retrieve_feature.py, brain/database/retrieve_session.py, brain/database/save_entity.py, brain/database/save_feature.py, brain/database/save_observation.py, puppet/environment/development/modules/database/scripts/setup_tables.py
=> #2526: Consistent yaml implementation for database

.travis.yml
=> #2504: Implement yaml linting

brain/session/base_data.py
=> #2584: base_data.py, reduce docblock

.travis.yml, hiera/settings.yaml, puppet/environment/development/modules/database/scripts/setup_tables.py
=> #2536: adjust 'model_type' in 'setup_tables.py'

puppet/environment/development/modules/sklearn/manifests/build_sklearn.pp
=> #2592: Increase 'timeout' for build in 'build_sklearn.pp'

puppet/environment/development/modules/compiler/scripts/browserify, puppet/environment/development/modules/compiler/scripts/imagemin, puppet/environment/development/modules/compiler/scripts/sass, puppet/environment/development/modules/compiler/scripts/uglifyjs
=> #2594: Webcompilers not generating asset files

puppet/environment/development/modules/compiler/scripts/browserify, puppet/environment/development/modules/compiler/scripts/imagemin, puppet/environment/development/modules/compiler/scripts/sass, puppet/environment/development/modules/compiler/scripts/uglifyjs, puppet/environment/development/modules/compiler/templates/webcompilers.erb
=> #2596: Interpolate yaml variables in compiler bash script

src/jsx/import/kernel/sv_kernel.jsx, src/jsx/import/model/model_type.jsx, src/jsx/import/session-type/data_append.jsx, src/jsx/import/session-type/data_new.jsx, src/jsx/import/session-type/model_generate.jsx
=> #2587: Move 'sv_model_type' component into dedicated jsx

Dockerfile, interface/static/data/json/programmatic_interface/svm/svm-data-append.json, interface/static/data/json/programmatic_interface/svr/svr-data-append.json
=> #2608: Eliminate 'session_name' from '***_data_append.json'

README.md, brain/converter/dataset/svr_json_converter.py, brain/session/data/dataset_to_dict.py, interface/static/data/json/programmatic_interface/svr/svr-data-append.json, interface/static/data/json/programmatic_interface/svr/svr-data-new.json, interface/static/data/json/web_interface/svr-1.json, interface/static/data/json/web_interface/svr.json
=> #2607: Ensure similar dataset structure across model types

brain/session/data/dataset_to_dict.py
=> #2611: Reduce syntax duplication in 'dataset_to_dict.py'

brain/converter/convert_dataset.py
=> #2613: Fix web-interface csv, xml parsers

brain/converter/dataset/svm_csv_converter.py, brain/converter/dataset/svm_xml_converter.py, brain/converter/dataset/svr_csv_converter.py, brain/converter/dataset/svr_json_converter.py, brain/schema/jsonschema_definition.py, brain/session/data/dataset_to_dict.py, brain/validator/validate_dataset.py
=> #2606: Remove trivial string validation in 'validate_dataset.py'

brain/database/save_entity.py, brain/session/data_append.py, brain/session/data_new.py, interface/static/data/json/programmatic_interface/svr/svr-data-new.json
=> #2602: Save 'model_type' within 'tbl_dataset_entity'

.travis.yml, docker/database.dockerfile, docker/default.dockerfile, docker/redis.dockerfile, docker/webserver.dockerfile
=> #2621: Lint all '*.dockerfile's

puppet/environment/docker/modules/compiler/manifests/initial_compile.pp, puppet/environment/docker/modules/compiler/manifests/start_browserify.pp, puppet/environment/docker/modules/compiler/manifests/start_imagemin.pp, puppet/environment/docker/modules/compiler/manifests/start_sass.pp, puppet/environment/docker/modules/compiler/manifests/start_uglifyjs.pp, puppet/environment/vagrant/modules/compiler/manifests/initial_compile.pp, puppet/environment/vagrant/modules/compiler/manifests/start_browserify.pp, puppet/environment/vagrant/modules/compiler/manifests/start_imagemin.pp, puppet/environment/vagrant/modules/compiler/manifests/start_sass.pp, puppet/environment/vagrant/modules/compiler/manifests/start_uglifyjs.pp
=> #2635: Fix 'dev_env_path' in compiler manifests

.gitignore, app.py, factory.py, interface/__init__.py, interface/views.py
=> #2638: Adjust existing 'app.py' to implement app factory

puppet/environment/docker/manifests/install_packages.pp, puppet/environment/docker/modules/package/manifests/pytest_flask.pp, puppet/environment/vagrant/manifests/install_packages.pp, puppet/environment/vagrant/modules/package/manifests/pytest_flask.pp
=> #2645: Replace 'pytest' with 'pytest-flask' package

.travis.yml, brain/cache/redis_settings.py, factory.py, puppet/environment/docker/manifests/configure_redis.pp, puppet/environment/docker/modules/redis/manifests/configuration.pp, puppet/environment/docker/modules/redis/templates/configuration.erb, test/hiera/settings.yaml
Resolves #2653.
**Note:** this merge request needs to be merged after #2628.
=> #2653: Configure 'redis.conf' to allow access to 'redis'

puppet/environment/vagrant/modules/webserver/manifests/service.pp
=> #2656: Properly build 'log_path' variable in 'service.pp'

puppet/environment/vagrant/modules/webserver/manifests/service.pp
=> #2656: service.pp, adjust 'log_path'

.travis.yml
=> #2660: Ensure docker '1.12.0' implemented in '.travis.yml'

.travis.yml, build_docker
Resolves #2662.
**Note:** this issue needs to be resolved after #2648.
=> #2662: Ensure proper definition in 'build_docker'

README.md
=> #2665: Update 'README.md' to correspond to #2648

README.md
=> #2667: Adjust 'Test Scripts' in 'README.md' for vagrant

README.md, hiera/packages.yaml, puppet/environment/docker/modules/package/manifests/webcompilers.pp, puppet/environment/vagrant/modules/package/manifests/webcompilers.pp
=> #2668: Implement hiera attributes in 'webcompilers.pp' 

.travis.yml, build_docker, factory.py, test/conftest.py
=> #2675: Ensure IOError, and failed unit test exit code is '1'

.travis.yml
=> #2675 .travis.yml, adjust comment

puppet/environment/docker/modules/system/manifests/set_timezone.pp, puppet/environment/vagrant/manifests/setup_database.pp, puppet/environment/vagrant/modules/database/manifests/bindings.pp, puppet/environment/vagrant/modules/database/manifests/client.pp, puppet/environment/vagrant/modules/database/manifests/server.pp, puppet/environment/vagrant/modules/system/manifests/set_timezone.pp
=> #2679: Properly contain puppet classes

brain/cache/cache_model.py, brain/session/model/svm.py, brain/session/model_predict.py, brain/session/predict/svm.py, interface/views.py
=> #2683: Remove 'rbf' term in 'svm_rbf_*' variables

Vagrantfile
=> #2689: Remove python cache on 'vagrant destroy'

Vagrantfile
=> #2689: Vagrantfile, remove double quotes

brain/session/model_generate.py, interface/static/data/json/programmatic_interface/svm/svm-model-generate.json, interface/static/data/json/programmatic_interface/svr/svr-model-generate.json
=> #2695: Web interface cannot use generated model

README.md, src/jsx/import/kernel/sv_kernel.jsx, src/jsx/import/session-type/model_generate.jsx
=> #2562: X.shape[0] should be equal to X.shape[1]

brain/converter/dataset/svm_xml_converter.py, brain/converter/dataset/svr_json_converter.py, brain/converter/dataset/svr_xml_converter.py
=> #2539: Create backend validator for SVR dataset(s)

brain/session/model/sv.py, brain/session/predict/sv.py, src/jsx/import/result/result_display.jsx, src/jsx/import/validator/valid_float.js
=> #1924: Determine svm confidence measurements

brain/session/model/sv.py, brain/session/predict/sv.py, src/jsx/import/result/result_display.jsx
=> #2704: Determine coefficient of determination

brain/converter/crypto.py, factory.py, hiera/settings.yaml, hiera/test/hiera/settings.yaml
=> #2700: crypto.py, implemented hash and verify functions with randomly generated salt

README.md
=> #2717: Adjust language typo in 'README.md'

brain/session/base_data.py, brain/session/data_append.py, brain/session/data_new.py, factory.py
=> #2709: Move 'self.uid' to 'factory.py'

brain/database/retrieve_feature.py, brain/database/save_feature.py, puppet/environment/docker/modules/database/scripts/setup_tables.py, puppet/environment/vagrant/modules/database/scripts/setup_tables.py
=> #2629: Split 'tbl_feature_value' into two tables

puppet/environment/docker/modules/database/scripts/setup_tables.py, puppet/environment/vagrant/modules/database/scripts/setup_tables.py
=> #2722: Index relevant tables in sql database

src/jsx/content.jsx, src/jsx/import/content/login.jsx, src/jsx/import/content/register.jsx, src/jsx/import/content/support_vector.jsx, src/jsx/import/navigation/nav_bar.jsx, src/jsx/import/navigation/user_menu.jsx
=> #2710: Create webform for user login / registration

puppet/environment/docker/modules/compiler/scripts/imagemin, puppet/environment/vagrant/modules/compiler/scripts/imagemin
=> #2741: Allow webcompilers to copy SVG images

brain/validator/validate_password.py, hiera/settings.yaml, hiera/test/hiera/settings.yaml, test/manual/authentication/pytest_validate_password.py
=> #2731, validate_password.py, creating new password validation script

brain/validator/validate_password.py, hiera/settings.yaml, hiera/test/hiera/settings.yaml, test/manual/authentication/pytest_validate_password.py
=> #2737: pytest_validate_password.py, unit tests for password validation

puppet/environment/docker/modules/database/scripts/setup_tables.py, puppet/environment/vagrant/modules/database/scripts/setup_tables.py
=> #2181: Define 'tbl_user' table in 'setup_tables.py'

interface/views.py, src/jsx/import/content/support_vector.jsx, src/jsx/import/input-data/supply_predictors.jsx
=> #2750: Webform unable to send POST request

puppet/environment/docker/modules/compiler/manifests/initial_compile.pp, puppet/environment/docker/modules/compiler/manifests/start_browserify.pp, puppet/environment/docker/modules/compiler/manifests/start_imagemin.pp, puppet/environment/docker/modules/compiler/manifests/start_sass.pp, puppet/environment/docker/modules/compiler/manifests/start_uglifyjs.pp, puppet/environment/docker/modules/compiler/manifests/webcompilers.pp, puppet/environment/docker/modules/compiler/scripts/browserify, puppet/environment/docker/modules/compiler/scripts/imagemin, puppet/environment/docker/modules/compiler/scripts/sass, puppet/environment/docker/modules/compiler/scripts/uglifyjs, puppet/environment/vagrant/modules/compiler/manifests/initial_compile.pp, puppet/environment/vagrant/modules/compiler/manifests/start_browserify.pp, puppet/environment/vagrant/modules/compiler/manifests/start_imagemin.pp, puppet/environment/vagrant/modules/compiler/manifests/start_sass.pp, puppet/environment/vagrant/modules/compiler/manifests/start_uglifyjs.pp, puppet/environment/vagrant/modules/compiler/manifests/webcompilers.pp, puppet/environment/vagrant/modules/compiler/scripts/browserify, puppet/environment/vagrant/modules/compiler/scripts/imagemin, puppet/environment/vagrant/modules/compiler/scripts/sass, puppet/environment/vagrant/modules/compiler/scripts/uglifyjs
=> #2673: Remove 'vagrant_implement' instances

puppet/environment/docker/modules/compiler/scripts/sass, puppet/environment/vagrant/modules/compiler/manifests/webcompilers.pp, puppet/environment/vagrant/modules/compiler/scripts/browserify, puppet/environment/vagrant/modules/compiler/scripts/sass
=> #2746: Ensure webcompiler persistence

puppet/environment/docker/modules/package/manifests/flask_script.pp, puppet/environment/vagrant/modules/package/manifests/flask_script.pp
=> #2760: Fix typo in flask installation script

src/jsx/import/svg/svg_menu.jsx
=> #2728: Add three bar SVG for navigation menu

.travis.yml
=> #2773: Add rst linting for documentation

.travis.yml
=> #2776: Trivial comment change in '.travis.yml'

src/jsx/import/content/login.jsx, src/scss/_user_menu.scss, src/scss/_webform.scss, src/scss/style.scss
=> #2734: Create nececssary scss definitions for login form

src/scss/_spinner.scss, src/scss/_variables.scss, src/scss/style.scss
=> #2786: Standardize color variables in '_variables.scss'

src/jsx/import/content/login.jsx, src/jsx/import/content/register.jsx
=> #2784: Ensure password 'input' hidden

src/jsx/content.jsx, src/jsx/import/content/support_vector.jsx, src/jsx/import/navigation/menu-items/menu_home.jsx, src/jsx/import/navigation/menu-items/menu_login.jsx, src/jsx/import/navigation/menu-items/menu_register.jsx, src/jsx/import/navigation/nav_bar.jsx, src/jsx/import/navigation/user_menu.jsx, src/jsx/router.jsx, src/scss/_user_menu.scss
=> #2727: Create application tray for main sessions

src/scss/_layout.scss, src/scss/_user_menu.scss
=> #2794: Add proper css margin for main container

src/jsx/import/content/support_vector.jsx, src/scss/_layout.scss, src/scss/_user_menu.scss, src/scss/_variables.scss, src/scss/_webform.scss
=> #2796: Remove sidebar session component persistence

.gitignore, README.md, documentation/index.rst
=> #2792: Create 'documentation/index.rst'

README.md, documentation/contribution/support.rst, documentation/programmatic_interface/data_attributes.rst, documentation/unit_test/pytest.rst
=> #2800: Enhance documentation by reducing 'README.md'

README.md
=> #2800: README.md, reduce language

interface/views.py, src/jsx/import/content/register.jsx, src/jsx/import/content/support_vector.jsx, src/jsx/import/input-data/supply_predictors.jsx, src/jsx/import/navigation/nav_bar.jsx, src/jsx/import/session-type/data_append.jsx, src/jsx/import/session-type/model_generate.jsx, src/jsx/import/session-type/model_predict.jsx, src/jsx/router.jsx
=> #2805: Redirect all requests to 'index.html'

brain/database/retrieve_account.py, interface/views.py, test/live_server/authentication/pytest_account_registration.py, test/live_server/authentication/pytest_user_login.py
=> #2810: Ensure username has unique email address

brain/database/retrieve_account.py, factory.py, hiera/settings.yaml, hiera/test/hiera/settings.yaml, interface/views.py
=> #2819: Implement flask 'session' for user login and logout

puppet/environment/docker/modules/compiler/manifests/start_sass.pp, puppet/environment/docker/modules/compiler/scripts/sass, test/live_server/authentication/pytest_user_login.py, test/live_server/authentication/pytest_user_logout.py
=> #2823: Create logout unit test

hiera/packages.yaml, puppet/environment/docker/manifests/start_webserver.pp, puppet/environment/docker/modules/package/manifests/gunicorn.pp, puppet/environment/vagrant/manifests/start_webserver.pp, puppet/environment/vagrant/modules/package/manifests/gunicorn.pp
=> #2764: Install uwsgi or gunicorn

test/live_server/programmatic_interface/dataset_url/pytest_svm_dataset_url.py, test/live_server/programmatic_interface/dataset_url/pytest_svr_dataset_url.py, test/live_server/programmatic_interface/file_upload/pytest_svm_file_upload.py, test/live_server/programmatic_interface/file_upload/pytest_svr_file_upload.py, test/manual/programmatic_interface/dataset_url/pytest_svm_dataset_url.py, test/manual/programmatic_interface/dataset_url/pytest_svr_dataset_url.py, test/manual/programmatic_interface/file_upload/pytest_svm_file_upload.py, test/manual/programmatic_interface/file_upload/pytest_svr_file_upload.py
=> #2826: Correctly adjust url refereneces in unit tests

brain/database/db_query.py
=> #2713: Ensure manual unit tests can be rerun

hiera/packages.yaml, puppet/environment/docker/Puppetfile, puppet/environment/docker/modules/webserver/manifests/service.pp, puppet/environment/vagrant/Puppetfile, puppet/environment/vagrant/modules/webserver/manifests/service.pp
=> #2465: Install nginx via puppet implementation

.travis.yml, factory.py, hiera/settings.yaml, hiera/test/hiera/settings.yaml, puppet/environment/docker/modules/webserver/manifests/service.pp, puppet/environment/docker/modules/webserver/manifests/start.pp, puppet/environment/docker/modules/webserver/templates/gunicorn.erb, puppet/environment/vagrant/modules/webserver/manifests/service.pp, puppet/environment/vagrant/modules/webserver/manifests/start.pp, puppet/environment/vagrant/modules/webserver/templates/gunicorn.erb
=> #2832: Implement gunicorn as a precursor to #2830

Vagrantfile
=> #2845: Implement custom trusty64 vagrant box

interface/templates/index.html, src/jsx/content.jsx, src/jsx/import/content/support_vector.jsx, src/jsx/import/main.jsx, src/jsx/import/navigation/nav_bar.jsx, src/jsx/router.jsx
=> #2807: Ensure react-routers on browser refresh

src/jsx/package.json
=> #2854: Add necessary redux packages to 'package.json'

src/jsx/content.jsx, src/jsx/import/content/login.jsx, src/jsx/import/main.jsx, src/jsx/import/navigation/menu-items/menu_login.jsx, src/jsx/import/navigation/user_menu.jsx, src/jsx/import/redux/action/login-action.jsx, src/jsx/import/redux/action/logout-action.jsx, src/jsx/import/redux/container/login-container.jsx, src/jsx/import/redux/container/menu-login-container.jsx, src/jsx/import/redux/load-storage.jsx, src/jsx/import/redux/reducer/login-reducer.jsx, src/jsx/import/redux/store.jsx, src/jsx/router.jsx
=> #2818: Add 'logout' button for 'logged-in' users

src/scss/_navigation.scss, src/scss/_variables.scss, src/scss/_webform.scss, src/scss/style.scss
=> #2866: Gently style analysis component

src/jsx/import/result/result_display.jsx, test/live_server/authentication/pytest_account_registration.py, test/live_server/authentication/pytest_user_login.py, test/live_server/authentication/pytest_user_logout.py, test/live_server/programmatic_interface/dataset_url/pytest_svm_dataset_url.py, test/live_server/programmatic_interface/dataset_url/pytest_svr_dataset_url.py, test/live_server/programmatic_interface/file_upload/pytest_svm_file_upload.py, test/live_server/programmatic_interface/file_upload/pytest_svr_file_upload.py, test/manual/authentication/pytest_crypto.py, test/manual/configure_database.py, test/manual/programmatic_interface/dataset_url/pytest_svm_dataset_url.py, test/manual/programmatic_interface/dataset_url/pytest_svr_dataset_url.py, test/manual/programmatic_interface/file_upload/pytest_svm_file_upload.py, test/manual/programmatic_interface/file_upload/pytest_svr_file_upload.py
=> #2751: Ensure 'programmatic_interface' tests more specific

contributing.json
=> #2714: Add 'gitmagic' custom rules

contributing.json, puppet/environment/docker/Puppetfile, puppet/environment/vagrant/Puppetfile
=> #2842: Determine nosql package via 'Puppetfile'

contributing.json, contributing.md, src/jsx/import/content/login.jsx, src/jsx/import/main.jsx, src/jsx/package.json
=> #2860: Redirect '/login' to frontpage when logged-in

puppet/environment/docker/Puppetfile, puppet/environment/vagrant/Puppetfile
=> #2888: define all 'Puppetfile' module version

src/jsx/import/content/register.jsx, src/jsx/import/main.jsx, src/jsx/import/redux/container/menu-login-container.jsx, src/jsx/import/redux/container/register-container.jsx, src/jsx/router.jsx
=> #2864: Redirect '/register' to frontpage if logged-in

src/jsx/content.jsx, src/jsx/import/content/home-page.jsx, src/jsx/router.jsx
=> #2850: Create frontpage for overall application

license.md
=> #2890: Extend 'license.md' to 2017

hiera/packages.yaml, src/jsx/content.jsx, src/jsx/import/content/login.jsx, src/jsx/import/content/register.jsx, src/jsx/import/navigation/menu-items/menu-home.jsx, src/jsx/import/navigation/menu-items/menu-login.jsx, src/jsx/import/navigation/menu-items/menu-register.jsx, src/jsx/import/navigation/user-menu.jsx, src/jsx/import/redux/container/menu-login-container.jsx, src/jsx/import/redux/container/menu-register-container.jsx, src/jsx/router.jsx
=> #2857: Allow redux to conditionally render usermenu

src/jsx/content.jsx, src/jsx/import/content/home-page.jsx, src/jsx/import/content/support-vector.jsx, src/jsx/import/layout/analysis-layout.jsx, src/jsx/import/layout/login-layout.jsx, src/jsx/import/layout/page-layout.jsx, src/jsx/import/layout/register-layout.jsx, src/jsx/import/navigation/menu-items/menu-home.jsx, src/jsx/import/navigation/menu-items/menu-login.jsx, src/jsx/import/navigation/menu-items/menu-register.jsx, src/jsx/import/navigation/user-menu.jsx, src/jsx/import/page-layout.jsx, src/jsx/import/redux/action/login-action.jsx, src/jsx/import/redux/action/page-action.jsx, src/jsx/import/redux/container/analysis-layout-container.jsx, src/jsx/import/redux/container/data-append-container.jsx, src/jsx/import/redux/container/data-new-container.jsx, src/jsx/import/redux/container/model-generate-container.jsx, src/jsx/import/redux/container/model-predict-container.jsx, src/jsx/import/redux/container/register-container.jsx, src/jsx/import/redux/reducer/login-reducer.jsx, src/jsx/import/redux/reducer/page-reducer.jsx, src/jsx/import/redux/store.jsx, src/jsx/import/session-type/data-append.jsx, src/jsx/import/session-type/data-new.jsx, src/jsx/import/session-type/model-generate.jsx, src/jsx/import/session-type/model-predict.jsx, src/jsx/router.jsx, test/lint/.jscs.json, test/lint/eslint.json
=> #2899: Ensure application renders in FF and IE

src/jsx/import/layout/analysis-layout.jsx, src/jsx/import/layout/page-layout.jsx
=> #2903: Ensure 'UserMenu' properly render menu-items

src/jsx/import/content/login.jsx, src/jsx/import/content/register.jsx, src/jsx/import/layout/page-layout.jsx, src/jsx/import/layout/register-layout.jsx, src/jsx/router.jsx
=> #2908: Remove duplicate '<div>' for layout pages

interface/views.py
=> #2907: Fix 404 error when hard loading URL in IE

puppet/environment/docker/modules/compiler/scripts/browserify, puppet/environment/vagrant/modules/compiler/scripts/browserify, src/jsx/import/content/support-vector.jsx, src/jsx/import/layout/analysis.jsx, src/jsx/import/redux/action/results.jsx, src/jsx/import/redux/container/analysis-layout.jsx, src/jsx/import/redux/container/data-append.jsx, src/jsx/import/redux/container/data-new.jsx, src/jsx/import/redux/container/model-generate.jsx, src/jsx/import/redux/container/results.jsx, src/jsx/import/redux/container/support-vector.jsx, src/jsx/import/redux/reducer/data.jsx, src/jsx/import/redux/reducer/page.jsx, src/jsx/import/redux/store.jsx, src/jsx/import/result/result-display.jsx, src/jsx/import/session-type/data-append.jsx, src/jsx/import/session-type/data-new.jsx, src/jsx/import/session-type/model-generate.jsx, src/jsx/import/session-type/model-predict.jsx, src/jsx/package.json, src/jsx/router.jsx
=> #2897: Create 'Prediction Result' page

src/jsx/import/input-data/supply-dataset-file.jsx, src/jsx/import/input-data/supply-dataset-url.jsx, src/jsx/import/session-type/data-new.jsx, src/jsx/import/session-type/model-predict.jsx
=> #2821: Resolve reactjs warnings (browser console)

src/jsx/import/content/support-vector.jsx, src/jsx/import/general/submit-button.jsx, src/jsx/import/input-data/supply-dataset-file.jsx, src/jsx/import/input-data/supply-dataset-url.jsx, src/jsx/import/result/result-display.jsx, src/jsx/import/session-type/data-new.jsx, src/jsx/import/session-type/model-predict.jsx
This pull request is the valid version and resolves #2915.
=> #2821: Resolve reactjs warnings (revert)

.travis.yml, puppet/environment/docker/modules/database/scripts/setup_tables.py, puppet/environment/vagrant/modules/database/scripts/setup_tables.py
=> #2871: Add necessary sql constructs for prediction

puppet/environment/docker/modules/database/scripts/setup_tables.py, puppet/environment/vagrant/modules/database/scripts/setup_tables.py
=> #2919: Add additional columns to prediction tables

src/jsx/import/input-data/supply-dataset-file.jsx, src/jsx/import/input-data/supply-dataset-url.jsx
=> #2918: Cannot add multiple dataset on web-interface

.travis.yml
=> #2940: .travis.yml, update 'libxml2-utils'

default.dockerfile
=> #2951: Fix 'git' install in 'default.dockerfile'

README.md, doc/background/puppetfile.rst, doc/configuration/ssh_keys.rst
=> #2849: Create 'preconfiguration' documentation

README.md
=> #2967: Add 'note' to 'Configuration' in 'README.md'

test/unit-tests
=> #2970: Reduce 'grep' syntax in 'unit-tests'

interface/views.py
=> #2872: views.py, remove 'user' argument

interface/views.py, src/jsx/import/navigation/menu-items/login.jsx
=> #2974: Fix flask 'session' logout

README.md, doc/programmatic_interface/data/data_append.rst, doc/programmatic_interface/data/data_new.rst, doc/programmatic_interface/data_attributes.rst, doc/programmatic_interface/model/model_generate.rst, doc/programmatic_interface/predict/model_predict.rst, doc/programmatic_interface/result/result_arbiter.rst, doc/programmatic_interface/result/retrieve_prediction.rst, doc/programmatic_interface/result/retrieve_prediction_titles.rst, doc/programmatic_interface/result/save_prediction.rst
=> #2979: Reorganize documentation and 'README.md'

doc/programmatic_interface/data/data_append.rst, doc/programmatic_interface/data/data_new.rst, doc/programmatic_interface/data_attributes.rst, doc/programmatic_interface/model/model_generate.rst, doc/programmatic_interface/predict/model_predict.rst, doc/programmatic_interface/result/retrieve_prediction.rst, doc/programmatic_interface/result/retrieve_prediction_titles.rst, doc/programmatic_interface/result/save_prediction.rst
=> #2979: data_attributes.rst, fix url references

brain/database/prediction.py, doc/programmatic_interface/result/retrieve_prediction.rst, interface/static/data/json/programmatic_interface/svm/results/retrieve-prediction.json, interface/static/data/json/programmatic_interface/svr/results/retrieve-prediction.json, interface/views.py, puppet/environment/docker/modules/mariadb/scripts/setup_tables.py, puppet/environment/vagrant/modules/mariadb/scripts/setup_tables.py
=> #2980: Refactor mariadb tables generically

.travis.yml, README.md, Vagrantfile, doc/programmatic_interface/data/data_append.rst, doc/programmatic_interface/data/data_new.rst, doc/programmatic_interface/model/model_generate.rst, doc/programmatic_interface/predict/model_predict.rst, doc/programmatic_interface/result/retrieve_prediction.rst, doc/programmatic_interface/result/retrieve_prediction_titles.rst, doc/programmatic_interface/result/save_prediction.rst, hiera/packages.yaml, hiera/test/hiera/webserver.yaml, hiera/webserver.yaml, puppet/environment/docker/modules/webserver/manifests/init.pp, puppet/environment/docker/modules/webserver/manifests/service.pp, puppet/environment/docker/modules/webserver/manifests/ssl.pp, puppet/environment/docker/modules/webserver/templates/ssl.erb, puppet/environment/vagrant/modules/webserver/manifests/init.pp, puppet/environment/vagrant/modules/webserver/manifests/service.pp, puppet/environment/vagrant/modules/webserver/manifests/ssl.pp, puppet/environment/vagrant/modules/webserver/templates/ssl.erb
=> #2837: Implement secured https url

Vagrantfile, default.dockerfile
=> #2961: Update vagrant box by ~512MB

default.dockerfile
=> #2991: Ensure 'r10k' properly installs for unit tests

puppet/environment/docker/modules/compiler/scripts/browserify, puppet/environment/vagrant/modules/compiler/scripts/browserify
=> #2989: Fix 'browserify' webcompiler by hardcoding

hiera/packages.yaml
=> #2996: Update nginx version in 'packages.yaml'

contributing.md
=> #2998: Adjust 'Contributing.md' sections

contributing.md
=> #3000: Fix minor typo in 'contributing.md'

interface/static/data/json/programmatic_interface/svm/file_upload/svm-data-append.json, test/live_server/programmatic_interface/file_upload/pytest_svr_file_upload.py
=> #3004: Fix programmatic-interface 'file_upload' case

brain/database/account.py, brain/database/dataset.py, brain/database/entity.py, brain/database/model_type.py, brain/database/prediction.py, brain/database/query.py, brain/database/session.py, factory.py
=> #2990: Create 'get_mariadb' in 'query.py'

default.dockerfile
=> #3014: Update 'git' package in 'default.dockerfile'

interface/views.py, src/jsx/import/content/login.jsx, src/jsx/import/content/register.jsx, src/scss/_variables.scss, src/scss/_webform.scss
=> #2812: Create frontend validator for login page

src/jsx/import/content/login.jsx
=> #3016: Ensure missing username yield login error

interface/views.py, src/jsx/import/content/login.jsx
=> #3018: Do not use serverside 'username' in login

brain/session/data_append.py
=> #3021: Remove entity removal from 'data_append.py'

.travis.yml, puppet/environment/docker/modules/compiler/scripts/browserify, puppet/environment/vagrant/modules/compiler/scripts/browserify
=> #3023: Update 'libxml2-utils' in '.travis.yml'

src/scss/style.scss
=> #3028: Fix input 'btn-primary' style

src/jsx/import/navigation/menu-items/login.jsx, src/jsx/import/navigation/user-menu.jsx, src/jsx/import/redux/action/logout.jsx, src/jsx/import/redux/container/login-link.jsx, src/jsx/import/redux/container/user-menu.jsx
=> #3045: Ensure '/logout' updates 'session' and react

src/jsx/import/navigation/menu-items/login.jsx, src/jsx/import/navigation/user-menu.jsx
=> #3045: user-menu.jsx, update redux correctly

src/jsx/import/content/login.jsx, src/jsx/import/content/register.jsx, src/jsx/import/layout/page.jsx, src/jsx/import/redux/action/page.jsx, src/jsx/import/redux/container/login.jsx, src/jsx/import/redux/container/page.jsx, src/jsx/import/redux/container/register.jsx, src/jsx/import/redux/reducer/page.jsx
=> #3051: Ensure after '/register' redirected to '/login'

brain/validator/email.py, interface/views.py, src/jsx/import/content/register.jsx, test/live_server/1_authentication/pytest_account_registration.py
=> #3052: Ensure all '/register' fields not null

brain/session/model/bagger.py, hiera/application.yaml, hiera/test/hiera/application.yaml
=> #3071: Add additional 'model_type'

src/jsx/import/content/home-page.jsx, src/jsx/import/content/login.jsx, src/jsx/import/content/register.jsx, src/jsx/import/general/spinner.jsx, src/jsx/import/general/submit-button.jsx, src/jsx/import/input-data/supply-dataset-file.jsx, src/jsx/import/input-data/supply-dataset-url.jsx, src/jsx/import/input-data/supply-predictors.jsx, src/jsx/import/kernel/sv-kernel.jsx, src/jsx/import/layout/analysis.jsx, src/jsx/import/layout/login.jsx, src/jsx/import/layout/page.jsx, src/jsx/import/layout/register.jsx, src/jsx/import/model/model-type.jsx, src/jsx/import/navigation/header-menu.jsx, src/jsx/import/navigation/menu-items/current-result.jsx, src/jsx/import/navigation/menu-items/home.jsx, src/jsx/import/navigation/menu-items/login.jsx, src/jsx/import/navigation/menu-items/menu.jsx, src/jsx/import/navigation/menu-items/register.jsx, src/jsx/import/navigation/menu-items/results.jsx, src/jsx/import/navigation/nav-bar.jsx, src/jsx/import/result/current-result.jsx, src/jsx/import/result/results.jsx, src/jsx/import/session-type/data-append.jsx, src/jsx/import/session-type/data-new.jsx, src/jsx/import/session-type/model-generate.jsx, src/jsx/import/session-type/model-predict.jsx, src/jsx/import/svg/svg-home.jsx
=> #3079: Change React.CreateClass to ES6 Class

default.dockerfile
=> #3085: Ensure 'wget' installs correctly within travis

puppet/environment/docker/Puppetfile, puppet/environment/vagrant/Puppetfile
=> #3090: Fix 'puppet-timezone' reference in 'Puppetfile'

hiera/packages.yaml
=> #3102: Ensure 'libssl-dev' properly installed

interface/static/data/json/programmatic_interface/bagr/file_upload/bagr-data-append.json, interface/static/data/json/programmatic_interface/bagr/file_upload/bagr-data-new.json, interface/static/data/json/web_interface/bagr-1.json, interface/static/data/json/web_interface/bagr.json
=> #3105: Ensure bagr dataset properties are float values

doc/programmatic_interface/authentication/login.rst
=> #3113: Remove anon reference from '/login' doc

brain/session/data/dataset.py
=> #3099: Fix json dataset submission on web-interface

mariadb.dockerfile, mongodb.dockerfile, redis.dockerfile, test/unit-tests, webserver.dockerfile
=> #2235: Create docker container for 'MariaDB'

test/unit-tests
=> #3097: Create docker container for 'mongodb'

test/unit-tests
=> #2237: Create docker container for 'redis'

test/unit-tests
=> #2236: Create docker container for 'webserver'

.travis.yml, test/linter
=> #2933: further migrate installation into bash script

src/scss/_navigation.scss
=> #2802: Highlight 'active' sidebar 'NavLink'

src/jsx/import/layout/analysis.jsx, src/jsx/import/redux/container/analysis-layout.jsx, src/jsx/import/redux/container/data-append.jsx, src/jsx/import/redux/container/model-generate.jsx, src/jsx/import/redux/container/model-predict.jsx, src/jsx/import/redux/container/results.jsx, src/jsx/import/result/results.jsx, src/jsx/import/session-type/data-append.jsx, src/jsx/import/session-type/model-generate.jsx, src/jsx/import/session-type/model-predict.jsx
=> #3058: Use redux to conditionally render spinner

src/jsx/import/input-data/supply-predictors.jsx, src/jsx/import/layout/analysis.jsx, src/jsx/import/layout/page.jsx, src/jsx/import/model/model-type.jsx, src/jsx/import/navigation/menu-items/current-result.jsx, src/jsx/import/navigation/nav-bar.jsx, src/jsx/import/session-type/data-append.jsx, src/jsx/import/session-type/data-new.jsx, src/jsx/import/session-type/model-generate.jsx, src/jsx/import/session-type/model-predict.jsx, src/scss/_layout.scss, src/scss/_navigation.scss, src/scss/_webform.scss, src/scss/style.scss
=> #3135: Adjust spacing on '/session' derived pages

src/jsx/import/layout/analysis.jsx, src/jsx/import/navigation/nav-bar.jsx
=> #3137: Consolidate bootstrap 'col-sm-x' classes

src/jsx/import/input-data/supply-dataset-file.jsx, src/jsx/import/input-data/supply-dataset-url.jsx, src/jsx/import/input-data/supply-predictors.jsx, src/jsx/import/layout/analysis.jsx, src/jsx/import/model/model-type.jsx, src/jsx/import/session-type/data-append.jsx, src/jsx/import/session-type/data-new.jsx, src/jsx/import/session-type/model-generate.jsx, src/jsx/import/session-type/model-predict.jsx, src/scss/_webform.scss
=> #3139: Apply 'form-control' on '/session' elements

doc/programmatic_interface/model/parameters/penalty.rst
=> #3131: Adjust documentation on 'penalty' parameter

brain/session/model/sv.py, brain/session/model_generate.py, doc/programmatic_interface/model/model_generate.rst, doc/programmatic_interface/model/parameters/gamma.rst, src/jsx/import/layout/analysis.jsx, src/jsx/import/redux/action/page.jsx, src/jsx/import/redux/container/analysis-layout.jsx, src/jsx/import/redux/reducer/page.jsx, src/jsx/import/session-type/model-generate.jsx
=> #3129: Implement optional 'gamma'

src/jsx/import/navigation/header-menu.jsx, src/jsx/import/navigation/user-menu.jsx
=> #3152: Move 'Review results' menu item under user icon

src/jsx/import/navigation/header-menu.jsx, src/jsx/import/navigation/user-menu.jsx, src/scss/_navigation.scss
=> #3156: Use 'SvgUserIcon' for 'Login' menu item

.travis.yml, src/jsx/import/layout/analysis.jsx, src/jsx/import/result/current-result.jsx, src/jsx/import/session-type/data-append.jsx, src/jsx/import/session-type/model-generate.jsx, src/scss/_layout.scss, src/scss/_navigation.scss, src/scss/_webform.scss, test/lint/.scss-lint.yml, test/linter
=> #3159: Ensure linter can return failed exit code

src/package.json
=> #3161: Update 'rearm' to eliminate console warning

src/jsx/import/layout/page.jsx, src/jsx/import/navigation/header-menu.jsx, src/jsx/import/navigation/user-menu.jsx, src/scss/_navigation.scss, src/scss/_navigation_authenticated.scss, src/scss/_variables.scss, src/scss/style.scss, test/lint/.scss-lint.yml
=> #3154: Implement authenticated 'className' for styling

src/scss/_navigation_authenticated.scss
=> #3154: properly close + open scss definitions

src/jsx/import/layout/analysis.jsx, src/scss/_layout.scss, src/scss/_navigation.scss, src/scss/_variables.scss, src/scss/_webform.scss, test/lint/.scss-lint.yml
=> #3165: Ensure left column spans entire height

src/jsx/import/layout/analysis.jsx
=> #3169: Use 'col-sm-2' on 'lcolumn-container'

src/package.json
=> #2298: Install D3.js for clientside graphs, and charts

src/jsx/import/layout/page.jsx, src/jsx/import/navigation/header-menu.jsx, src/scss/_layout.scss, src/scss/_navigation.scss, src/scss/_navigation_authenticated.scss, src/scss/_variables.scss, src/scss/_webform.scss
=> #3172: Remove unnecessary 'container' header class

puppet/environment/docker/modules/compiler/scripts/browserify, puppet/environment/vagrant/modules/compiler/scripts/browserify, src/package.json
=> #3180: Update with 'babel-preset-env'

.travis.yml, brain/schema/dataset.py, puppet/environment/docker/Puppetfile, puppet/environment/docker/modules/package/manifests/nodejs.pp, puppet/environment/vagrant/Puppetfile, src/package.json
=> #3187: Fix 'package.json' peer dependency

brain/validator/settings.py, src/jsx/import/general/range-slider.jsx, src/jsx/import/redux/action/page.jsx, src/jsx/import/redux/container/analysis-layout.jsx, src/jsx/import/redux/reducer/page.jsx, src/jsx/import/session-type/model-generate.jsx
=> #3192: Add optional 'gamma' + 'penalty' validation

src/jsx/import/general/range-slider.jsx
=> #3194: range-slider.jsx, remove redux slider value

src/jsx/import/layout/analysis.jsx, src/package.json
=> #3191: Present backend exceptions with react

brain/session/data/dataset.py, brain/validator/dataset.py
=> #3201: Fix compounding 'voluptuous' errors

doc/programmatic-interface/authentication/login.rst, doc/programmatic-interface/data-attributes.rst, doc/programmatic-interface/data/data-append.rst, doc/programmatic-interface/data/data-new.rst, doc/programmatic-interface/model/model-generate.rst, doc/programmatic-interface/predict/model-predict.rst, doc/programmatic-interface/result/retrieve-prediction-titles.rst, doc/programmatic-interface/result/retrieve-prediction.rst, doc/programmatic-interface/result/save-prediction.rst, doc/test/lint.rst, doc/test/pytest.rst
=> #3205: implement relative paths

.travis.yml, app.py, docker-compose.development.yml, dockerfile/browserify.dockerfile, dockerfile/mariadb.dockerfile, dockerfile/mongodb.dockerfile, dockerfile/nginx.dockerfile, dockerfile/sass.dockerfile, dockerfile/webserver.dockerfile, factory.py, hiera.yaml, hiera/reverse-proxy/nginx-api.yaml, hiera/reverse-proxy/nginx-web.yaml, hiera/webserver/webserver-api.yaml, hiera/webserver/webserver-web.yaml, install_rancher, interface/templates/index.html, puppet/environment/docker/modules/mariadb/manifests/server.pp, puppet/environment/docker/modules/reverse_proxy/manifests/config.pp, puppet/environment/docker/modules/reverse_proxy/manifests/init.pp, puppet/environment/docker/modules/reverse_proxy/manifests/params.pp, puppet/environment/docker/modules/webserver/manifests/config.pp, puppet/environment/docker/modules/webserver/manifests/install.pp, puppet/environment/docker/modules/webserver/templates/entrypoint.erb, rancher-template.development.yml, test/linter, test/unit-tests
=> #2935: Replace puppet 'docker' with containers

dockerfile/browserify.dockerfile, dockerfile/nginx.dockerfile, puppet/environment/docker/modules/mongodb/manifests/config.pp, puppet/environment/docker/modules/sklearn/manifests/install.pp, test/linter
=> #3220: Fix current travis ci linting errors

README.md, doc/installation/dependencies.rst, doc/installation/rancher.rst
=> #3222: Fix link references in doc + 'README.md'

README.md, doc/installation/rancher.rst
=> #3222: Use '.html' extension, add screenshots

doc/installation/dependencies.rst
=> #3222: dependencies.rst, compress language

README.md, doc/programmatic-interface/authentication/login.rst, doc/programmatic-interface/data/data-append.rst, doc/programmatic-interface/data/data-new.rst, doc/programmatic-interface/model/model-generate.rst, doc/programmatic-interface/predict/model-predict.rst, doc/programmatic-interface/result/retrieve-prediction-titles.rst, doc/programmatic-interface/result/retrieve-prediction.rst, doc/programmatic-interface/result/save-prediction.rst
=> #3222: update 'localhost' with correct endpoint

README.md
=> #3222: README.md, prefix with 'https://'

doc/installation/rancher.rst
=> #3222: Fix docker installation link

README.md
=> #3222: README.md, remove broken link

doc/installation/rancher.rst
=> #3222: rancher.rst, minor language change

install_rancher
=> #3233: Ensure rancher build works on windows 10

src/jsx/__tests__/layout/page.test.jsx
=> #3237: Adjust 'page.test.jsx' test descriptions

install_rancher
=> #3262: Ensure 'install_rancher' runs on trusty64

install_rancher
=> #3264: Implement bash error testing in 'install_rancher'

README.md
=> #3266: Fix links in 'README.md'

doc/installation/docker-compose.rst, doc/installation/rancher.rst, doc/programmatic-interface/authentication/login.rst, doc/programmatic-interface/data/data-append.rst, doc/programmatic-interface/data/data-new.rst, doc/programmatic-interface/model/model-generate.rst, doc/programmatic-interface/predict/model-predict.rst, doc/programmatic-interface/result/retrieve-prediction-titles.rst, doc/programmatic-interface/result/retrieve-prediction.rst, doc/programmatic-interface/result/save-prediction.rst, docker-compose.rancher.yml, docker-compose.yml, dockerfile/base.dockerfile, test/backend
=> #3268: Change nginx ports + adjust documentation

src/jsx/import/route/main-route.jsx
=> #3273: Fix css alignment on various pages

hiera/packages.yaml
=> #3260: Determine associative mining packages

dockerfile/base.dockerfile, src/jsx/__tests__/content/login.test.jsx, src/jsx/__tests__/content/register.test.jsx, src/jsx/__tests__/layout/analysis.test.jsx, src/jsx/__tests__/layout/page.test.jsx, src/jsx/jest.config.js, src/jsx/package.json
=> #2412: Update to Ubuntu 16.04
