html/machine-learning/test/xml/sample.xml

#816: Create XML equivalent for 'sample.csv'

---

html/machine-learning/test/csv/sample-1.csv

#842: sample-1.csv, change 'dep-variable-label'

---

html/machine-learning/test/csv/sample.csv

#841: sample.csv, change 'dep-variable-label'

---

html/machine-learning/test/xml/sample-1.xml

#817: Create XML equivalent for 'sample-1.csv'

---

html/machine-learning/test/csv/sample-1.csv

#847: sample-1.csv, ensure lowercase labels

---

html/machine-learning/test/csv/sample.csv

#846: sample.csv, ensure lowercase labels

---

html/machine-learning/test/xml/sample.xml

#816: sample.xml, correct xml declaration

---

html/machine-learning/test/xml/sample-1.xml

#817: sample.xml, correct xml declaration

---

src/js/html_form.js

#837: Add SVM title input text field to 'html_form.js'

---

src/js/html_form.js

#853: Move form fields in 'html_form.js'

---

src/js/form_validator.js

#838: Validate 'svm_title' field in 'form_validator.js'

---

html/machine-learning/test/php/index.php

#858: Change datalist to selectlist in 'index.php'

---

html/machine-learning/test/php/index.php

#858: index.php, add default option value

---

src/js/html_form.js

#856: Change datalist to selectlist in 'html_form.js'

---

src/js/ajax_json.js

#864: ajax_json.js, remove use of 'datalist'

---

html/machine-learning/php/load_logic.php

#862: load_logic.php, remove 'datalist' related logic

---

python/config.py

#839: Validate 'svm_title' field in 'config.py'

---

python/data_creator.py

#836: Restructure dataset tables in 'data_creator.py'

---

python/data_creator.py

#869: data_creator.py, return unique ID of last inserted row

---

html/machine-learning/test/php/index.php

#875: index.php, remove 'ajax_json.min.js' reference

---

html/machine-learning/php/load_logic.php

#872: load_logic.php, change 'properties' -> 'settings'

---

html/machine-learning/php/load_logic.php

#881: Remove 'json_creator' definition

---

python/config.py

#883: Remove schema definition for 'json_creator'

---

python/data_validator.py

#873: Adjust validation logic in 'data_validator.py'

---

python/svm_training.py

#886: svm_training.py, correct value for 'svm_dataset'

---

python/svm_training.py

#886: svm_training.py, account for list

---

python/data_validator.py

#873: Adjust iteration logic in 'data_validator.py'

---

python/config.py

#874: Adjust validation schema in 'config.py'

---

python/data_validator.py

#873: data_validator.py, 'import jsonschema_dataset_id'

---

python/svm_training.py

#886: svm_training.py, change 'json.dumps' -> 'json_loads'

---

html/machine-learning/php/load_logic.php

#895: load_logic.php, properly general 'svm session type'

---

python/data_creator.py

#894:   Properly INSERT into 'tbl_dataset_value'

---

python/config.py

#874: Adjust validation for 'jsonschema_analysis'

---

python/config.py

#874: config.py, add missing commas

---

python/data_validator.py

#899: Replace error 'print' statements in 'data_validator.py'

---

python/svm_training.py

#904: Properly get validation return in 'svm_training.py'

---

python/data_validator.py

#906: data_validator.py, append each error message

---

python/data_creator.py

#908: Replace error 'print' statements in 'data_creator.py'

---

python/svm_training.py

#898: Store multiple csv uploads properly

---

README.md

#823: Adjust generic sample of dict input element

---

python/data_creator.py

#911: data_creator.py, adjust docblock

---

README.md

#823: README.md, minor stylistic changes

---

html/machine-learning/test/php/index.php

#928: Adjust initial form elements in 'index.php'

---

src/js/form_validator.js

#930: Adjust validator for 'svm_session'

---

src/js/html_form.js

#156: Adjust logic for 'Configuration' fieldset

---

src/js/html_form.js

#917: html_form.js, add 'svm_session_id'

---

src/js/html_form.js

#934: html_form.js, generate submit button

---

src/js/form_validator.js

#919: Validate 'svm_session_id' in 'form_validator.js'

---

src/js/html_form.js

#937: html_form.js, ensure no space delimitation

---

src/js/form_validator.js

#939: form_validator.js, 'svm_dataset_type' validation

---

src/js/form_validator.js

#939: form_validator.js, add missing comma

---

python/config.py

#924: config.py, add 'svm_session' id validation schema

---

python/config.py

#942: config.py, adjust validation for 'svm_dataset_type'

---

python/config.py

#925: config.py, adjust definition for 'svm_session'

---

html/machine-learning/php/load_logic.php

#946: Adjust array definitions in 'load_logic.php'

---

html/machine-learning/php/load_logic.php

#948: load_logic.php, adjust nested 'if-else' statements

---

python/data_upload.py

#953: change import statement respectively

---

python/data_uploader.py

#956: Rename 'data_upload.py' -> 'data_uploader.py'

---

html/machine-learning/php/load_logic.php

#957: load_logic.php, adjust to reference new filename

---

README.md

#960 - Documentation: Adjust 'Programmatic Interface'

---

html/machine-learning/php/load_logic.php

#964: load_logic.php, change file reference

---

python/data_saver.py

#920: Change 'uid' to 'uid_created' in 'data_creator.py'

---

python/data_saver.py

#921: Change 'datetime_saved' in 'data_creator.py'

---

python/data_saver.py

#922: Add 'uid_modified' column to 'tbl_dataset_entity'

---

python/data_saver.py

#923: Add 'datetime_modified' to 'tbl_dataset_entity'

---

src/js/html_form.js

#976: Add 'svm_dataset_type' in 'html_form.js'

---

python/config.py

#982: config.py, adjust 'svm_session' schema validation

---

html/machine-learning/test/php/index.php

#973: index.php, add '<script>' for 'ajax_session.js'

---

src/js/ajax_session.js

#971: Create 'ajax_session.js'

---

src/js/ajax_data.js

#1001: ajax_data.js, remove ajax animation during error

---

src/js/html_form.js

#1006: Call 'session_id()' function in 'html_form.js'

---

src/js/ajax_session.js

#971: ajax_session.js, encapsulate ajax object

---

src/js/html_form.js

#1006: html_form.js, minor language changes

---

src/js/ajax_session.js

#971: ajax_session, fix minor typo

---

html/machine-learning/php/settings.php

#1011: Add 'settings.php' similar to 'config.py'

---

html/machine-learning/php/retriever_session.php

#972: Create 'retriever_session.php'

---

src/js/ajax_session.js

#971: ajax_session.js, adjust array keys in 'each' loop

---

html/machine-learning/php/retriever_session.php

#972: retriever_session.php, use get methods

---

src/js/html_form.js

#977: Add 'fieldset_supply_dataset' fieldset

---

src/js/html_form.js

#1018: html_form.js, replace 'text()' -> 'val()'

---

src/js/html_form.js

#978: html_form.js, add submit button

---

src/js/html_form.js

#1021: Replace "none" with "" in 'html_form.js'

---

html/machine-learning/test/php/index.php

#1022: index.php, replace 'none' -> ''

---

src/js/html_form.js

#1021: html_form.js, remove unnecessary 'console.log()'

---

src/js/form_validator.js

#919: form_validator.js, validate select 'value' as integer

---

src/js/html_form.js

#1027: html_form.js, convert analysis to 'generate model'

---

src/js/html_form.js

#984: html_form.js, add 'svm_model_id'

---

src/js/form_validator.js

#985: form_validator.js, validation for 'svm_model_id'

---

src/js/html_form.js

#984: html_form.js, replace 'svm_model_id'

---

html/machine-learning/test/php/index.php

#992: index.php, add 'ajax_model.min.js' reference

---

src/js/html_form.js

#1033: html_form.js, properly add 'session_id' values

---

src/js/html_form.js

#1035: html_form.js, remove '!== -1'

---

src/js/html_form.js

#1037: Add 'submit' for 'Generate Model' session

---

src/js/html_form.js

#1035: html_form.js, add '!== -1' logic

---

src/js/html_form.js

#987: html_form.js, create 'fieldset_session_analysis'

---

src/js/html_form.js

#983: html_form.js, add 'svm_model_type'

---

src/js/html_form.js

#974: html_form.js, remove 'svm_model_type'

---

src/js/html_form.js

#986: Adjust removal of 'svm_model_type' in 'html_form.js'

---

src/js/html_form.js

#900: Remove 'Use Model' for other selections

---

python/session_model_generate.py

#152: Create skeleton 'session_model_generate.py' file

---

python/session_data_append.py

#1049: session_data_append.py, add empty skeleton file

---

python/session_model_generate.py

#152: session_model_generate.py, language change

---

html/machine-learning/php/settings.php

#1055: settings.php, change 'public' -> 'protected'

---

html/machine-learning/php/settings.php

#1055: settings.php, revert methods back to 'public'

---

python/session_model_use.py

#1048: session_model_use.py, minor language change

---

python/session_data_append.py

#1049: session_data_append.py, language change

---

python/session_model_use.py

#1048: session_model_use.py, language change

---

html/machine-learning/php/connector_python.php

#1050: Adjust 'shell_command' in 'connector_python.php'

---

html/machine-learning/php/connector_python.php
html/machine-learning/php/load_logic.php

#1066: Fix 'Internal 500 Server Error' in 'load_logic.php'

---

html/machine-learning/php/load_logic.php

#1066: load_logic.php, partial undo for e7879d1

---

python/session_data_new.py

#1047: session_data_new.py, adjust docblock

---

python/load_logic.py

#1051: Create 'load_logic.py'

---

html/machine-learning/php/connector_python.php

#1074: connector_python.php, add space character

---

python/session_data_new.py

#1077: session_data_new.py, 'return flag_quit'

---

python/session_data_new.py

#1077: session_data_new.py, add 'validate_mime_type'

---

python/session_data_new.py

#1077: Remove 'sys.argv[1]' and fix 'check_arg_length'

---

python/session_data_new.py

#1077: session_data_new.py, correct method definition

---

python/session_data_new.py

#1077: session_data_new.py, undo 5b82972

---

python/session_data_new.py

#1077: slightly adjust 'dataset_to_json'

---

python/load_logic.py

#1080: Correctly implement 'Data_New' in 'load_logic.py'

---

python/session_data_new.py

#1096: session_data_new.py, adjust 'import'

---

python/data_validator.py

#1094: data_validator.py, change 'config' -> 'jsonschema'

---

python/data_validator.py

#1094: data_validator.py, use to 'jsonschema_definition'

---

python/session_data_append.py

#1103: session_data_append.py, add skeleton class

---

python/session_model_generate.py

#1091: session_model_generate.py, add skeleton class

---

python/session_model_use.py

#1092: Add skeleton class in 'session_model_use.py'

---

python/session_data_new.py

#1077: Adjust 'validation_check_return'

---

python/session_data_new.py

#1108: Change 'check_arg_length'

---

python/load_logic.py

#1080: load_logic.py, implement 'validate_arg_none'

---

python/session_data_new.py

#1090: session_data_new.py, define method docblocks

---

python/session_data_new.py

#1112: Return responses in 'session_data_new.py'

---

python/session_data_new.py

#1112: Adjust error responses in 'session_data_new.py'

---

python/session_data_new.py

#1112: session_data_new.py, implement 'flag_append'

---

python/session_data_new.py

#1112: Remove flags in 'session_data_new.py'

---

python/load_logic.py

#1080: Adjust class method calls in 'load_logic.py'

---

python/load_logic.py

#1080: load_logic.py, adjust 'session.return_error'

---

python/data_validator.py

#1119: Adjust 'self.svm_session' in 'data_validator.py'

---

python/data_validator.py

#1128: Ensure 'data_validation' works in 'data_validator.py'

---

python/session_data_new.py

#1130: Remove 'training' parameter in 'session_data_new.py'

---

python/session_model_use.py

#1131: Remove unncessary parameter

---

python/session_data_new.py

#1134: Fix 'self.json_dataset' iteration

---

python/data_validator.py

#1128: Correctly assing 'svm_session'

---

python/session_model_use.py

#1131: session_model_use.py, use 'self.svm_session'

---

python/session_data_new.py

#1134: session_data_new.py, fix typo

---

python/load_logic.py

#1080: load_logic.py, remove 'print session_type'

---

python/session_data_new.py

#1144: session_data_new.py, remove 'None' default value

---

python/jsonschema_definition.py

#1140: Rename jsonschemas definitions

---

python/data_validator.py

#1141: data_validator.py, adjust schema calls

---

python/data_validator.py
python/validator_settings.py

#1124: Move 'data_validation' from 'data_validator.py'

---

python/validator_mime.py

#1125: validator_mime.py, remove unnecessary 'import'

---

python/validator_settings.py

#1124: validator_settings.py, remove 'import'

---

python/session_data_new.py

#1154: Adjust 'import' in 'session_data_new.py'

---

python/validator_settings.py

#1124: validator_settings.py, import jsonschema

---

python/jsonschema_definition.py

#1157: Create definitions in 'jsonschema_definitions.py'

---

python/session_model_use.py

#1159: Adjust 'session_model_use.py'

---

python/session_data_new.py

#1161: Add argument in 'session_data_new.py'

---

python/session_data_new.py

#1161: session_data_new.py, rename parameters

---

python/data_saver.py

#1163: data_saver.py, adjust 'INSERT' statement

---

python/load_logic.py

#1144: Implement session classes in 'load_logic.py'

---

python/load_logic.py

#1174: Implement 'Data_Add' methods in 'load_logic.py'

---

python/session_data_add.py

#1177: Define 'set_entity_id' in 'session_data_add.py'

---

python/session_data_add.py

#1180: session_data_new.py, fix 'validate_arg_none'

---

python/load_logic.py

Partial #1182, Resolves #1184.

#1182, #1184: load_logic.py, fix 'arg_none' typo

---

python/session_data_add.py

#1180: session_data_add.py, remove 'self.flag_quit'

---

python/load_logic.py

#1184: load_logic.py, revert 'arg_none' logic

---

python/session_data_add.py

#1183: Define 'check' method in 'session_data_add.py'

---

python/data_saver.py

#1188: data_saver.py, return consistent object with 'rowid'

---

html/machine-learning/php/connector_python.php

#1050: connector_python.php, fix path to 'load_logic.py'

---

package/validator/validator_mime.py

#1193: validator_mime.py, adjust 'import' for 'md5_for_file'

---

src/js/form_validator.js

#645: form_validator.js, add 'text/xml' to 'checkMime'

---

package/validator/validator_mime.py

#1200: validator_mime.py, add 'text/xml'

---

.gitignore

#181: .gitignore, adjust file according to 'package/'

---

package/session/session_data_add.py

#1203: session_data_add.py, iterate dataset (xml)

---

package/load_logic.py

#1080: load_logic.py, pass 'session_type'

---

package/session/session_data_add.py

#1212: Define 'session_type' in 'session_data_add.py'

---

package/database/data_saver.py

#1213: Redefine 'Training' class in 'data_saver.py'

---

package/session/session_data_add.py

#1212: session_data_add.py, add forgotten 'session_type'

---

package/load_logic.py

#1080: load_logic.py, pass 'session_type' for entity

---

package/load_logic.py

#1222: load_logic.py, invoke 'session.save_svm_entity()'

---

package/database/data_saver.py

#1213: Correctly implement 'UPDATE' in 'data_saver.py'

---

README.md

#778: README.md, add 'UPDATE' to 'mariadb database'

---

package/load_logic.py

#1222: load_logic.py, pass 'session_id' argument

---

package/session/session_data_add.py

#1226: session_data_add.py, implement 'session_id'

---

package/database/data_saver.py

#1213: data_saver.py, use 'id_entity' in 'UPDATE'

---

package/session/session_data_add.py

#1226: session_data_add.py, 'session_type == data_new'

---

package/session/session_data_add.py

#1226: session_data_add.py, add minor comment

---

package/database/data_saver.py

#1213: data_saver.py, remove unused 'self.uid'

---

package/validator/validator_mime.py

#1233: Correctly return data in 'validator_mime.py'

---

package/session/session_data_add.py

#1234: session_data_add.py, correspond to #1233

---

package/validator/validator_mime.py

#1233: validator_mime.py, fix typo in file docblock

---

package/schema/jsonschema_definition.py

#1167: jsonschema_definition.py, fix minor typo

---

package/session/session_data_add.py

#1246: session_data_add.py, fix docblock redundancies

---

package/session/session_model_use.py

#1245: session_model_use.py, fix docblock redundancies

---

package/database/data_saver.py

#1252: data_saver.py, adjust 'import' statement

---

package/database/db_settings.py

#1251: db_settings.py, adjust filename in docblock

---

package/database/db_query.py

#1250: Create 'db_query.py'

---

package/database/db_query.py

#1250: db_query.py, fix minor docblock typo

---

package/database/db_query.py

#1250: db_query.py, fix 'DB.error' typos

---

package/database/db_query.py

#1250: db_query.py, initialize 'self.list_error' in constructor

---

package/database/db_query.py

#1250: db_query.py, add 'database' argument

---

package/database/db_query.py

#1250: db_query.py, prefix argument as 'db=database'

---

package/database/data_saver.py

#1258: Adjust SQL logic in 'data_saver.py'

---

package/database/data_saver.py

#1258: Adjust docblock in 'data_saver.py'

---

package/converter/converter_md5.py

#1191: converter_md5.py, remove 'duplicate_list_index'

---

package/session/session_base.py

#1243: Create superclass 'session_base.py'

---

package/session/session_base.py

#1243: session_base.py, supply 'object' argument

---

package/session/session_data_add.py

#1267: Implement 'session_base.py'

---

package/session/session_base.py

#1243: session_base.py, adjust class docblock

---

package/session/session_model_use.py

#1092: session_model_use.py, explicitly inherit new-style class

---

package/validator/validator_dataset.py

#1272: validator_dataset.py, explicitly inherit 'new-style' class

---

package/validator/validator_mime.py

#1274: validator_mime.py, explicitly inherit 'new-style' class

---

package/validator/validator_settings.py

#1276: validator_settings.py, inherit 'new-style' class

---

package/database/data_saver.py

#1278: data_saver.py, inherit 'new-style' class

---

package/database/db_query.py

#1250: db_query.py, inherit 'new-style' class

---

package/database/db_settings.py

#1281: inherit new-style class in 'db_settings.py'

---

package/converter/converter_json.py

#1283: converter_json.py, inherit 'new-style' class

---

package/session/session_data_add.py

#1267: eliminate redundancies in 'session_data_add.py'

---

package/session/session_data_add.py

#1267: session_data_add.py, add forgotten 'svm_data'

---

package/validator/validator_settings.py

#1123: validator_settings.py, validate 'data_append' case

---

package/schema/jsonschema_definition.py

#1142: jsonschema_definition.py, 'data_append' schema

---

package/session/session_data_append.py

#1291: session_data_append.py, rename class

---

package/session/session_data_append.py

#1291: add 'self.svm_data' in 'session_data_append.py'

---

package/session/session_data_append.py

#1291: session_data_append.py, remove 'self.svm_data'

---

package/session/session_data_new.py

#1244: Create 'session_data_new.py'

---

package/session/session_data_append.py

#1291: session_data_append.py, correctly use 'super()'

---

package/session/session_data_new.py

#1244: session_data_new.py, require 'session_id'

---

package/session/session_data_new.py

#1244: session_data_new.py, remove 'session_id'

---

package/session/session_data_new.py

#1244: restructure 'save_svm_entity'

---

package/session/session_data_append.py

#1291: session_data_append.py, add method

---

package/session/session_data_append.py
package/session/session_data_new.py

#1302: Reverse superclass in 'session_data_new.py'

---

package/session/session_data_append.py

#1291: fix 'return' logic in 'session_data_append.py'

---

package/load_logic.py

#1174: Implement split session classes in 'load_logic.py'

---

package/session/session_data_new.py

#1306: session_data_new.py, add missing colon(s)

---

package/session/session_data_append.py

#1291: session_data_append.py, fix superclass

---

package/load_logic.py

#1174: correctly test for the 'session_entity'

---

package/session/session_data_append.py

#1291: session_data_append.py, 'import json'

---

package/session/session_data_append.py

#1291: session_data_append.py, 'import' training class

---

package/load_logic.py

#1174: load_logic.py, remove 'session.set_entity_id'

---

package/session/session_data_append.py

#1291: session_data_append.py, update docblock

---

package/database/data_saver.py

#1314: data_saver.py, remove 'Analysis' class

---

package/database/data_saver.py

#1316: Rename class in 'data_saver.py'

---

package/session/session_data_new.py

#1317: session_data_new.py, fix class, and methods

---

package/session/session_data_append.py

#1320: session_data_append.py, fix class, and methods

---

package/session/session_model_use.py

#1159: session_model_use.py, remove 'import Analysis'

---

package/database/data_saver.py

#1316: data_saver.py, fix indentation

---

package/database/data_saver.py

#1316: data_saver.py, rename 'db_save_data'

---

package/session/session_data_new.py

#1317: session_data_new.py, respective fix for ee19e1a

---

package/session/session_data_append.py

#1320: session_data_append.py, fix for ee19e1a

---

package/database/data_saver.py

#1316: data_saver.py, minor language changes

---

package/database/data_saver.py

#1316: data_saver.py, move 'self.list_error'

---

package/database/data_retriever.py

#1249: Create 'data_retriever.py'

---

package/database/data_saver.py

#1316: fix method, comment, docblock in 'data_saver.py'

---

package/database/db_query.py

#1331: db_query.py, adjust 'sql_command()' docblock

---

package/converter/converter_md5.py

#1334: Adjust docblock, and import in 'converter_md5.py'

---

package/database/data_retriever.py

#1337: data_retriever.py, define docblock

---

package/database/data_saver.py

#1336: data_saver.py, define docblock

---

package/database/data_retriever.py

#1337: data_retriever.py, minor grammatical change

---

package/database/db_query.py

#1333: Define 'select' case in 'db_query.py'

---

package/database/db_query.py

#1333: db_query.py, use 'self.cursor.fetchall()'

---

package/database/data_retriever.py

#1343: data_retriever.py, remove 'id: response[id]' return

---

package/database/data_retriever.py

#1343: data_retriever.py, reverse 'response[result]'

---

package/load_logic.py

#1346: load_logic.py, define, and implement 'session_id'

---

package/load_logic.py

#1346: load_logic.py, change 'get_dataset'

---

README.md

#619: Update 'Linux Packages'

---

package/database/data_saver.py

#1354: 'tbl_feature_label' definition in 'data_saver.py'

---

package/database/data_saver.py

#1354: data_saver.py, add missing colon

---

package/converter/converter_json.py
package/parser/parser_feature_label.py

#1358: Create 'get_feature_labels' in 'converter_json.py'

---

package/session/session_data_new.py

#1357: Define 'save_feature_label' 

---

package/database/data_saver.py

#1354: use 'delete', correctly return in 'data_saver.py'

---

package/load_logic.py

Partial #1349.  Allows, us to resume with https://github.com/jeff1evesque/machine-learning/issues/1080#issuecomment-73834420.

#1349: load_logic.py, 'format_dataset()'

---

package/database/data_saver.py

#1366: Rename 'get_feature_labels' in 'data_saver.py'

---

package/converter/converter_json.py

#1365: Rename 'get_feature_labels'

---

package/converter/converter_json.py

#1365: converter_json.py, initialize 'indep_variable_label'

---

package/session/session_data_new.py

#1357: rename 'feature_labels' -> 'observation_labels'

---

package/database/data_saver.py

#1372: data_saver.py, rename 'id_attribute' -> 'id_value'

---

package/load_logic.py

#1080: implement 'save_observation_label'

---

package/load_logic.py

#1174: load_logic.py, use 'save_observation_label'

---

package/database/db_query.py

#1379: db_query.py, update using 'interview-meetup'

---

src/js/form_validator.js

#1378: form_validator.js, validate 'svm_dataset'

---

package/session/session_base.py

#1243: session_base.py, minor language change

---

package/session/session_base_data.py

#1360: Create 'session_base_data.py'

---

package/session/session_base_data.py

#1360: session_base_data.py, rename class

---

package/session/session_base.py
package/session/session_data_new.py

#1243: Correctly implement 'Base' superclass

---

package/session/session_data_new.py

#1361: Remove methods in 'session_data_new.py'

---

package/session/session_data_new.py

#1361: Inherit 'Base_Data' in 'session_data_new.py'

---

package/database/data_retriever.py

#1353: data_retriever.py, remove arguments

---

package/database/data_saver.py

#1375: Adjust 'data_append' observation label

---

html/machine-learning/test/php/index.php

#1390: index.php, implement 'autocomplete=off' attribute

---

__init__.py
bash/__init__.py
bash/database/__init__.py
html/machine-learning/__init__.py

#1396: Add '__init__.py' for various directories

---

README.md

#1398: README.md, implement flask

---

README.md

#1402: README.md, update links in 'Web Interface'

---

README.md

#1398: README.md, adjust 'Web Interface'

---

README.md

#480: README.md, update 'Bash Script'

---

.gitignore

#549: .gitignore, ignore 'sass-cache' relative to #1395

---

.gitignore

#181: gitignore, ignore 'build/' compiled python scripts

---

html/machine-learning/app.py

#1399: Create flask 'app.py'

---

.gitignore

#1421: gitignore, ignore compiled asset directories

---

build/bash_loader

#1394: Update 'bash_loader' haystack directories

---

src/js/form_validator.js

#1378: form_validator.js, remove validation

---

html/machine-learning/templates/index.html

#1401: index.html, change 'load-data/' -> '/load-data/'

---

html/machine-learning/package/__init__.py

#1426: __init__.py, add file in web 'package/' directory

---

.gitmodules

#1430: Move 'scikit-learn' submodule

---

.gitignore

#1433: gitignore, readjust with respect to new structure

---

.gitignore

#1433: gitignore, ignore files relative to 'mlearning/'

---

.gitignore

#1433: '.gitignore', adjust corresponding to #1430

---

brain/__init__.py

#1430: __init__.py, add file to '/var/www/brain/'

---

build/web/web_img
build/web/web_js
build/web/web_scss

#1400: Adjust compilation directories for 'web_xx'

---

src/scss/style.scss

#603: style.scss, adjust reference to 'loading.gif'

---

.gitignore

#1433: .gitignore, do not ignore '/src/' directory

---

web_interface/views.py

#1445: views.py, adjust 'load_data' router

---

web_interface/views.py

#1445: Define 'Convert_Data' class invocation

---

src/js/ajax_session.js

#1407: Adjust 'url' implementation in 'ajax_session.js'

---

brain/database/data_retriever.py

#1455: data_retriever.py, implement 'self.sql'

---

brain/database/session_retriever.py

#1404: session_retriever.py, implement 'self.sql', fix typo

---

brain/database/data_saver.py

#1456: Ensure 'self.sql' class variable in 'data_saver.py'

---

web_interface/views.py

#1451: views.py, define router function 'retrieve_session'

---

brain/database/data_retriever.py
brain/database/data_saver.py
brain/database/db_query.py
brain/load_data.py
brain/session/session_base.py
brain/session/session_base_data.py
brain/session/session_data_append.py
brain/session/session_data_new.py
brain/session/session_model_use.py
brain/validator/validator_dataset.py
brain/validator/validator_mime.py
brain/validator/validator_settings.py

#1453: Adjust 'import' statements for brain python scripts

---

brain/load_data.py

#1462: load_data.py, define 'get_session_type'

---

brain/load_data.py

#1464: Create 'get_errors' in 'load_data.py'

---

brain/validator/validator_dataset.py
web_interface/views.py

#1453: Further adjust 'import' statements for brain

---

web_interface/views.py

#1445: Invoke 'Load_Data' class methods in 'views.py'

---

brain/load_data.py

#1467: load_data.py, adjust 'return' logic in 'check_json'

---

web_interface/views.py

#1467: views.py, add outer 'else' condition

---

.gitignore

#1471: .gitignore, adjust first comment

---

.gitignore

#1473: .gitignore, remove '/log/'

---

brain/converter/converter_data.py

#1449: Create 'converter_data.py'

---

brain/converter/converter_data.py

#1406: Merge variables, comments in 'converter_data.py'

---

brain/converter/converter_data.py

#1405: Adopt 'helper.php' into 'converter_data.py'

---

brain/converter/converter_data.py

#1406: Adopt 'connector_python.php'

---

web_interface/views.py

#1479: views.py, 'import json'

---

build/database/setup_db.py

#1214: setup_db.py, minor comment change

---

bash/database/setup_db.py

#1214: build, remove duplicated directory

---

setup.py

#1487: Create 'setup.py' in project root

---

.gitignore

#1489: .gitignore, add exception for 'setup.py'

---

brain/load_data.py

#1467: load_data.py, remove 'check_json' method

---

web_interface/views.py

#1445: properly send data to brain

---

brain/load_data.py

#1493: load_data.py, remove 'json.loads()'

---

brain/load_data.py

#1464: load_data.py, 'return' non-dict value in 'get_errors'

---

brain/load_data.py

#1462: load_data.py, properly reference 'self.session_list'

---

brain/session/session_base.py

#1497: session_base.py, remove 'json_loads'

---

brain/load_data.py

#1493: load_data.py, remove 'import json'

---

brain/validator/validator_settings.py

#1500: Remove 'json.loads()' in 'validator_settings.py'

---

brain/validator/validator_settings.py

#1500: Reinsert 'json_data' as 'svm_settings'

---

brain/validator/validator_mime.py

#1503: Remove 'json.loads()' in 'validator_mime.py'

---

brain/validator/validator_mime.py

#1233: validator_mime.py, remove 'status' from 'return'

---

brain/session/session_base_data.py

#1506: session_base_data.py, remove 'self.svm_data'

---

brain/converter/converter_data.py

#1406: converter_data.py, 'formatted_files' list of dicts

---

brain/converter/converter_data.py

#1406: converter_data.py, readjust 'formatted_files' keys

---

brain/validator/validator_mime.py

#1510: Correctly hash 'file-uploads'

---

brain/validator/validator_mime.py

#1510: validator_mime.py, implement 'md5_for_object'

---

brain/converter/converter_md5.py

#1515: Remove file 'open' logic in 'converter_md5.py'

---

brain/converter/converter_md5.py

#1515: converter_md5.py, rename 'md5_for_file'

---

brain/validator/validator_mime.py

#1510: 'import md5_for_object' in 'validator_mime.py'

---

brain/session/session_base_data.py

#1519: session_base_data.py, remove 'json.loads()'

---

README.md

#619: README.md, remove 'python-magic'

---

brain/validator/validator_mime.py

#1510: build 'dataset_keep' in 'validator_mime.py'

---

brain/session/session_base_data.py

#1523: session_base_data.py, adjust method calls

---

brain/session/session_data_new.py

#1525: Define 'dataset_to_json' in 'session_data_new.py'

---

src/scss/style.scss

#1528: style.scss, adjust '.ajax_loader' url attribute

---

brain/session/session_base_data.py

#1527: session_base_data.py, adjust 'super'

---

brain/converter/converter_md5.py

#1515: converter_md5.py, adjust docblock, comments

---

brain/converter/converter_json.py

#457: converter_json.py, properly build 'list_data'

---

brain/converter/converter_json.py

#1534: converter_json.py, remove 'json' implementation

---

brain/session/session_base_data.py

#1523: session_base_data.py, properly method calls

---

brain/session/session_base_data.py

#1523: session_base_data.py, remove '!= None'

---

brain/session/session_base_data.py

#1538: session_base_data.py, correct return

---

brain/load_data.py

#1540: Add 'return' logic in 'load_data.py'

---

brain/converter/converter_json.py

#1543: converter_json.py, correctly adjust 'csv_to_json'

---

web_interface/views.py

#1445: views.py, use 'json.dumps()' in 'load_data'

---

brain/database/data_saver.py

#1542: data_saver.py, adjust 'return' for 'save_label'

---

web_interface/views.py

#1547: Implement 'Retrieve_Session' class in 'views.py'

---

brain/database/session_retriever.py

#1549: session_retriever.py, format 'session_list'

---

brain/session/session_data_append.py

#1551: session_data_append.py, remove 'json'

---

brain/converter/converter_json.py

#1555: Close each file-upload in 'converter_json.py'

---

brain/database/data_saver.py

#1557: data_saver.py, remove 'import datetime'

---

brain/database/db_query.py

#1554: db_query.py, adjust class docblock

---

brain/database/data_saver.py
brain/database/db_query.py
brain/database/db_settings.py
brain/database/retrieve_dataset.py
brain/database/retrieve_session.py
brain/load_data.py
brain/schema/jsonschema_definition.py
brain/session/base.py
brain/session/base_data.py
brain/session/data_append.py
brain/session/data_new.py
brain/session/model_generate.py
brain/session/model_use.py
brain/validator/validate_dataset.py
brain/validator/validate_mime.py
brain/validator/validate_settings.py
web_interface/views.py

#1560:  Implement PEP suggestions

---

brain/load_data.py

#1554: load_data.py, replace 'xx_xx_json' calls

---

src/scss/style.scss

#1166: style.scss, adjust 'margin' for 'fieldset'

---

src/scss/style.scss

#1566: Add 'margin-top' for 'submit' button in 'style.scss'

---

src/scss/variable.scss

#655: variable.scss, define 'form-margin'

---

src/scss/style.scss

#1570: Implement 'form-margin' in 'style.scss'

---

brain/validator/validate_mime.py

#1577: validate_mime.py, adjust indentation in 'validate'

---

brain/validator/validate_mime.py

#1577: validate_mime.py, remove 'print yes'

---

brain/database/save_dataset.py
brain/database/save_entity.py
brain/database/save_label.py
brain/session/base_data.py
brain/session/data_append.py
brain/session/data_new.py
brain/validator/validate_mime.py

#1575: Split up 'save_dataset.py'

---

brain/session/base_data.py
brain/session/data_new.py

#1581: Move 'save_observation_label'

---

brain/session/base_data.py
brain/session/data_new.py

#1583: Move 'dataset_to_dict' into 'base_data.py'

---

brain/session/data_append.py
brain/session/data_new.py

#1584: Change base classes for 'data_append.py'

---

brain/validator/validate_settings.py

#1587: validate_settings.py, use 'self.svm_settings.py'

---

brain/session/base.py

#1589: base.py, adjust docblock for 'Base' class

---

brain/session/base_data.py

#1591: base_data.py, adjust docblock for 'Base_Data'

---

brain/session/base_data.py

#1593: Remove 'super' implementation in 'base_data.py'

---

brain/session/data_append.py

#1595: Correctly implement 'super' in 'data_append.py'

---

brain/session/data_new.py

#1597: data_new.py, adjust constructor docblock

---

brain/session/data_append.py

#1599: data_append.py, adjust constructor docblock

---

brain/validator/validate_settings.py

#1290: validate_settings.py, remove xml validation

---

src/js/html_form.js

#976: html_form.js, change 'xml_url' -> 'dataset_url'

---

src/js/form_validator.js

#939: form_validator.js, validate 'dataset_url'

---

brain/schema/jsonschema_definition.py

#1602: jsonschema_definition.py, adjust for 'dataset_url'

---

src/js/html_form.js

#976: html_form.js, adjust 'placeholder' value

---

brain/validator/validate_dataset.py

#1607: Bypass 'check_schema' in 'validate_dataset.py'

---

brain/validator/validate_settings.py

#1608: Bypass 'check_schema' in 'validate_settings.py'

---

brain/load_data.py

#1349: load_data.py, remove 'session_id'

---

brain/database/retrieve_dataset.py

#1613: retrieve_dataset.py, remove 'self.svm_data'

---

brain/database/retrieve_dataset.py

#1615: retrieve_dataset.py, correcly implement 'self.sql'

---

brain/load_data.py

#1349: load_data.py, change 'format_dataset'

---

brain/session/model_generate.py

#1072: model_generate.py, remove 'Session_Base'

---

build/database/setup_tables_mlearning.py

#1620: Create 'tbl_dataset_size'

---

build/database/setup_database.py
build/database/setup_tables_mlearning.py

#1560: Implement PEP suggestions

---

brain/load_data.py
brain/session/base_data.py

Partial #1611, Resolves #1624.

Python base data

---

brain/session/base_data.py

#1624: base_data.py, change 'save_info' -> 'save_size'

---

brain/database/save_size.py

#1621: Create 'save_size.py'

---

brain/database/save_size.py

#1621: save_size.py, adjust 'return'

---

web_interface/views.py

#1633: views.py, adjust post logic in 'load_data'

---

brain/load_data.py

#1625: Implement 'save_svm_info' in 'load_data.py'

---

brain/session/base_data.py
brain/session/model_generate.py

#1636: Move 'save_svm_info' into 'model_generate.py'

---

brain/session/base_data.py
brain/session/model_generate.py

#1636: Move 'save_svm_info' into 'base_data.py'

---

brain/load_data.py

#1625: load_data.py, implement 'save_svm_info'

---

brain/session/base_data.py

#1636: base_data.py, properly implement 'Save_Size'

---

brain/converter/convert_upload.py

#1641: Incorporate feature count in 'convert_upload.py'

---

brain/converter/convert_upload.py

#1641: convert_upload.py, change overall docblock

---

brain/session/base_data.py

#1644: base_data.py, append 'count_features'

---

brain/session/base_data.py

#1646: Implement 'save_svm_info' in 'base_data.py

---

brain/converter/convert_upload.py

#1641: convert_upload.py, initialize 'self.count_features'

---

brain/session/base_data.py

#1646: Implement 'save_svm_info' in 'base_data.py'

---

brain/database/save_dataset.py

#1650: save_dataset.py, 'response' -> 'response_error'

---

brain/database/save_size.py

#1652: save_size.py, 'response' -> 'response_error'

---

brain/database/save_dataset.py
brain/database/save_entity.py
brain/database/save_size.py

#1654: Remove 'id' for return error case

---

brain/database/save_size.py

#1621: save_size.py, reference 'tbl_dataset_size'

---

brain/database/save_size.py
build/database/setup_tables_mlearning.py

#1657: Rename 'tbl_dataset_size' -> 'tbl_feature_count'

---

brain/converter/convert_upload.py
brain/load_data.py
brain/schema/jsonschema_definition.py
brain/session/base_data.py
brain/session/data_append.py
brain/session/data_new.py
brain/validator/validate_dataset.py

#1611: Granular dataset validation

---

brain/session/base.py
brain/session/base_data.py
brain/session/data_append.py
brain/session/model_generate.py
brain/session/model_use.py

#1659: Ensure 'self.list_error' consistency

---

brain/database/db_query.py
brain/database/retrieve_dataset.py
brain/database/retrieve_session.py
brain/database/save_dataset.py
brain/database/save_entity.py
brain/database/save_label.py
brain/database/save_size.py
brain/session/base.py

#1663: Implement consistent 'get_errors' method

---

brain/session/base_data.py
brain/session/data_append.py

#1669: Change all instances of 'uid' to 'self.uid'

---

brain/database/retrieve_dataset.py
brain/database/save_feature.py
build/database/setup_tables_mlearning.py

#1667: Rename 'tbl_dataset_value' to 'tbl_feature_value'

---

build/database/setup_database.py
build/database/setup_tables_mlearning.py

#1663: Implement consistent database 'get_errors'

---

brain/session/data_new.py

#1669: data_new.py, define 'self.uid' in constructor

---

brain/load_data.py
brain/session/base_data.py

#1679: Remove 'session_type' argument

---

build/database/setup_tables_mlearning.py

#1674: setup_tables_mlearning.py, add descriptions

---

web_interface/static/data/json/sample.json

#1683: Create 'sample.json'

---

web_interface/static/data/json/sample-1.json

#1684: sample-1.json, add file

---

README.md

#1685: Add 'json' to acceptable syntax in 'README.md'

---

web_interface/static/data/json/sample.json

#1683: sample.json, implement double quotes

---

brain/converter/convert_upload.py
brain/session/base_data.py
brain/validator/validate_mime.py
src/js/form_validator.js
src/js/html_form.js

#1662: Allow json file upload

---

brain/converter/convert_upload.py

#1662: convert_upload.py, correctly define feature count

---

brain/session/base_data.py
brain/session/data_append.py
brain/session/data_new.py

#1695: Save observation labels in 'base_data.py'

---

brain/database/retrieve_session.py
src/js/ajax_session.js
web_interface/views.py

#1681: Ensure empty 'data_append' does not hang

---

web_interface/views.py

#1698: Define docblock in 'views.py'

---

brain/database/retrieve_feature.py

#1700: retrieve_feature.py, change 'get_feature'

---

brain/database/retrieve_feature.py

#1700: retrieve_feature.py, adjust docblock

---

brain/database/save_observation.py

#1701: save_observation.py, adjust class docblock

---

brain/session/model_generate.py

#726: Adjust docblock, and comments

---

README.md

#619: README.md, install 'python-memcached'

---

brain/memcached/memcached_settings.py

#1710: memcached_settings.py, add file

---

brain/memcached/memcached_interface.py

#1711: memcached_interface.py, add file

---

brain/memcached/__init__.py

#1396: __init__.py, add file in '/brain/memcached/'

---

brain/memcached/memcached_interface.py

#1711: memcached_interface.py, adjust 'import'

---

.gitignore

#1489: .gitignore, add exception for 'settings.py'

---

README.md

#779: README.md, add note in 'GIT Submodule'

---

README.md

#512: README.md, update reference to 'scikit-learn'

---

brain/memcached/memcached_settings.py

#1710: memcached_settings.py, add correct content

---

brain/database/db_settings.py
brain/memcached/memcached_settings.py
settings.py

#1712: Create 'settings.py'

---

README.md

#1726: README.md, correctly reference 'db_settings.py'

---

README.md

#1725: README.md, update 'JSON Schema' linked texts

---

README.md

#1725: README.md, minor grammatical changes

---

README.md

#1723: Update 'Bash Script' subsection in 'README.md'

---

README.md

#1724: README.md, correctly link 'app.py'

---

README.md

#619: README.md, 'sudo pip install redis'

---

README.md

#1737: Add 'redis-server' to 'linux packages'

---

brain/cache/redis_query.py

#1736: redis_query.py, minor comment changes

---

brain/cache/redis_query.py

#1742:   Add 'start', and 'shutdown' methods

---

brain/cache/redis_query.py

#1744: Add 'bgsave' method to 'redis_query.py'

---

README.md

#1714: Add 'Redis' subsection in 'README.md'

---

README.md

#1714: Minor language changes in 'README.md'

---

README.md

#1714: README.md, minor language change

---

README.md

#619: Update comments in 'Linux Packages'

---

README.md

#1753: README.md, add 'six' to 'linux packages'

---

brain/converter/serialize_model.py

#1752: Create 'serialize_model.py'

---

brain/converter/serialize_model.py

#1752: serialize_model.py, adjust overall docblock

---

brain/converter/serialize_model.py

#1752: serialize_model.py, define class wrapper

---

brain/cache/cache_model.py

#1759: Create 'cache_model.py'

---

brain/cache_model.py

#1759: cache_model.py, adjust class docblock

---

brain/converter/serialize_model.py

#1752: serialize_model.py, adjust class docblock

---

brain/redis_query.py

#1761: Improve redis concurrent client connections

---

brain/redis_query.py

#1761: redis_query.py, correctly implement 'self.db_num'

---

README.md

#1714: More information on 'redis' in 'README.md'

---

README.md

#1771: Consolidate 'Redis' in 'README.md' to wiki

---

README.md

#1771: Minor language change for 'Redis'

---

brain/session/model_generate.py

#1707: Implement 'cache_model.py'

---

brain/cache/cache_model.py

#1759: cache_model.py, adjust indentation

---

brain/converter/serialize_model.py

#1752: serialize_model.py, adjust indentation

---

.gitignore

#181: .gitignore, ignore '/brain/cache/*.pyc'

---

brain/converter/serialize_model.py

#1752: serialize_model.py, remove unnecessary 'obj' argument

---

brain/cache/cache_model.py

#1781: cache_model.py, use correct arguments

---

brain/converter/serialize_model.py

#1783: serialize_model.py, 'import svm'

---

brain/cache/redis_query.py
brain/cache/redis_settings.py
brain/session/model_generate.py
settings.py

#1785: Fix unresponsive 'redis-py' client operation

---

README.md

#1771: Additional information on redis-server 'autostart'

---

src/js/html_form.js

#1789:  Implement 'model_id' function in 'html_form.js'

---

web_interface/views.py

#1792: Define '/retrieve_model/' router function

---

web_interface/views.py

#1792: import 'Retrieve_Model'

---

brain/cache/cache_model.py

#1759: cache_model.py, remove 'uncache' method

---

web_interface/views.py

#1792: views.py, implement 'Uncache_Model'

---

brain/cache/cache_model.py

#1759: cache_model.py, minor comment change

---

brain/cache/uncache_model.py

#991: Create 'uncache_model.py

---

web_interface/views.py

#1792: views.py, fix minor typo in 'retrieve-model'

---

web_interface/views.py

#1792: views.py, use 'svm_model' argument

---

brain/cache/uncache_model.py

#991: uncache_model.py, implement 'try-except'

---

brain/cache/cache_model.py

#1805: cache_model.py, implement 'try-except'

---

brain/session/model_generate.py

#1707: model_generate.py, adjust 'cache' argument

---

brain/cache/uncache_model.py

#991: uncache_model.py, parse for id, title

---

src/js/html_form.js

#1811: Remove unnecessary 'svm_model_type'
